// Command gencontracts generates code and documentation from the error catalog.
//
// Everything it writes is a build artifact: never hand-edit the output. CI runs
// this and fails if the working tree changes, which is what stops the catalog
// and the implementation drifting apart.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type errorDef struct {
	Code    string   `yaml:"code"`
	HTTP    int      `yaml:"http"`
	GRPC    string   `yaml:"grpc"`
	Message string   `yaml:"message"`
	When    string   `yaml:"when"`
	Remedy  string   `yaml:"remedy"`
	Details []string `yaml:"details"`
}

type catalog struct {
	Version int        `yaml:"version"`
	Errors  []errorDef `yaml:"errors"`
}

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	raw, err := os.ReadFile(filepath.Join(root, "contracts/errors/catalog.yaml"))
	must(err)

	var c catalog
	must(yaml.Unmarshal(raw, &c))
	sort.Slice(c.Errors, func(i, j int) bool { return c.Errors[i].Code < c.Errors[j].Code })

	must(os.WriteFile(filepath.Join(root, "services/api/internal/platform/apierr/codes_gen.go"), []byte(goFile(c)), 0o644))
	must(os.MkdirAll(filepath.Join(root, "packages/core/src"), 0o755))
	must(os.WriteFile(filepath.Join(root, "packages/core/src/errors.gen.ts"), []byte(tsFile(c)), 0o644))
	must(os.MkdirAll(filepath.Join(root, "docs/errors"), 0o755))
	for _, e := range c.Errors {
		must(os.WriteFile(filepath.Join(root, "docs/errors", e.Code+".md"), []byte(docPage(e)), 0o644))
	}
	fmt.Printf("generated %d error codes -> Go, TypeScript, %d doc pages\n", len(c.Errors), len(c.Errors))
}

func goFile(c catalog) string {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/gencontracts from contracts/errors/catalog.yaml. DO NOT EDIT.\n\npackage apierr\n\n")
	b.WriteString("// CatalogEntry is the published description of one error code.\ntype CatalogEntry struct {\n\tCode    Code\n\tHTTP    int\n\tGRPC    string\n\tMessage string\n\tDetails []string\n}\n\n")
	b.WriteString("// Catalog is every code in contracts/errors/catalog.yaml, keyed by code.\nvar Catalog = map[Code]CatalogEntry{\n")
	for _, e := range c.Errors {
		b.WriteString(fmt.Sprintf("\t%s: {Code: %s, HTTP: %d, GRPC: %q, Message: %q, Details: %s},\n",
			ident(e.Code), ident(e.Code), e.HTTP, e.GRPC, e.Message, goSlice(e.Details)))
	}
	b.WriteString("}\n")
	return b.String()
}

func goSlice(xs []string) string {
	if len(xs) == 0 {
		return "nil"
	}
	q := make([]string, len(xs))
	for i, x := range xs {
		q[i] = fmt.Sprintf("%q", x)
	}
	return "[]string{" + strings.Join(q, ", ") + "}"
}

// ident maps a SCREAMING_SNAKE code to the Go constant already declared in
// apierr.go, so the generated catalog references real constants and the
// compiler catches any code that was added to YAML but not to the package.
func ident(code string) string {
	parts := strings.Split(strings.ToLower(code), "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	s := strings.Join(parts, "")
	switch s {
	case "InvalidCoordinates":
		return "InvalidCoordinate"
	}
	return s
}

func tsFile(c catalog) string {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/gencontracts from contracts/errors/catalog.yaml. DO NOT EDIT.\n\n")
	b.WriteString("export const GHANAGEO_ERROR_CODES = [\n")
	for _, e := range c.Errors {
		b.WriteString(fmt.Sprintf("  %q,\n", e.Code))
	}
	b.WriteString("] as const;\n\nexport type GhanaGeoErrorCode = (typeof GHANAGEO_ERROR_CODES)[number];\n\n")
	b.WriteString("export interface ErrorCatalogEntry {\n  readonly http: number;\n  readonly grpc: string;\n  readonly message: string;\n  readonly details: readonly string[];\n}\n\n")
	b.WriteString("export const ERROR_CATALOG: Record<GhanaGeoErrorCode, ErrorCatalogEntry> = {\n")
	for _, e := range c.Errors {
		d := "[]"
		if len(e.Details) > 0 {
			q := make([]string, len(e.Details))
			for i, x := range e.Details {
				q[i] = fmt.Sprintf("%q", x)
			}
			d = "[" + strings.Join(q, ", ") + "]"
		}
		b.WriteString(fmt.Sprintf("  %s: { http: %d, grpc: %q, message: %q, details: %s },\n",
			e.Code, e.HTTP, e.GRPC, e.Message, d))
	}
	b.WriteString("};\n")
	return b.String()
}

func docPage(e errorDef) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n<!-- Generated from contracts/errors/catalog.yaml. DO NOT EDIT. -->\n\n", e.Code)
	fmt.Fprintf(&b, "| | |\n|---|---|\n| **HTTP status** | `%d` |\n| **gRPC status** | `%s` |\n\n", e.HTTP, e.GRPC)
	fmt.Fprintf(&b, "%s\n\n## When this happens\n\n%s\n\n## How to fix it\n\n%s\n\n", e.Message, e.When, e.Remedy)
	if len(e.Details) > 0 {
		b.WriteString("## Fields in `error.details`\n\n")
		for _, d := range e.Details {
			fmt.Fprintf(&b, "- `%s`\n", d)
		}
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "## Example\n\n```json\n{\n  \"error\": {\n    \"code\": %q,\n    \"message\": %q,\n    \"requestId\": \"req_01K3Y…\",\n    \"docs\": \"/docs/errors/%s\"\n  }\n}\n```\n", e.Code, e.Message, e.Code)
	return b.String()
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}
