/* Generated by scripts/docs-sdk/generate.mjs. Do not edit. */
export const SDK_API_VERSION = "v1" as const;
export const SDK_TESTED_DATASET_VERSION = "2026.08.3-ulid" as const;
export const SDK_EXAMPLES = [
  {
    "id": "typescript",
    "label": "TypeScript",
    "source": "scripts/docs-sdk/examples/typescript.ts",
    "install": "pnpm add @ghanageo/client",
    "runtime": "Node.js 22+ / modern browsers",
    "protocols": [
      "REST",
      "GraphQL"
    ],
    "cancellation": "AbortSignal",
    "retry": "Two safe-read retries; max five",
    "pagination": "Async page and item iterators",
    "errors": "GhanaGeoError",
    "code": "import { GhanaGeoClient, GhanaGeoError } from \"@ghanageo/client\";\n\nexport async function quickStart(signal?: AbortSignal) {\n  const client = new GhanaGeoClient();\n\n  try {\n    const page = await client.search(\"Kumasi\", { limit: 5 }, signal);\n    for (const place of page.data) console.log(place.name);\n  } catch (error) {\n    if (error instanceof GhanaGeoError) console.error(error.code, error.requestId);\n    else throw error;\n  }\n}"
  },
  {
    "id": "react",
    "label": "React",
    "source": "packages/react/examples/next16/app/page.tsx",
    "install": "pnpm add @ghanageo/react @tanstack/react-query",
    "runtime": "React 18.3+ / 19",
    "protocols": [
      "REST"
    ],
    "cancellation": "TanStack Query AbortSignal",
    "retry": "Client retry policy",
    "pagination": "Infinite-query page helpers",
    "errors": "GhanaGeoError",
    "code": "import { dehydrate, QueryClient } from \"@tanstack/react-query\";\nimport { GhanaGeoClient, ghanaGeoKeys } from \"@ghanageo/react\";\nimport { Providers } from \"./providers\";\n\nexport default async function Page() {\n  const queryClient = new QueryClient();\n  const client = new GhanaGeoClient();\n  await queryClient.prefetchQuery({\n    queryKey: ghanaGeoKeys.regions(),\n    queryFn: ({ signal }) => client.regions({}, signal),\n  });\n\n  return <Providers state={dehydrate(queryClient)}>Your hydrated location UI</Providers>;\n}"
  },
  {
    "id": "python",
    "label": "Python",
    "source": "sdks/python/examples/async_search.py",
    "install": "pip install ghanageo",
    "runtime": "Python 3.10+",
    "protocols": [
      "REST"
    ],
    "cancellation": "asyncio task cancellation",
    "retry": "RetryConfig; max five",
    "pagination": "Async page iterators",
    "errors": "GhanaGeoError",
    "code": "import asyncio\n\nfrom ghanageo import AsyncGhanaGeo\n\n\nasync def main() -> None:\n    async with AsyncGhanaGeo() as client:\n        page = await client.search(\"Kumasi\", limit=5)\n        for result in page.data:\n            print(result.id, result.name)\n\n\nasyncio.run(main())"
  },
  {
    "id": "go",
    "label": "Go",
    "source": "sdks/go/example_test.go",
    "install": "go get github.com/ghanageo/ghanageo-go",
    "runtime": "Go 1.23+",
    "protocols": [
      "REST"
    ],
    "cancellation": "context.Context",
    "retry": "Functional retry option; max five",
    "pagination": "Next(ctx), Page(), Err()",
    "errors": "*ghanageo.Error",
    "code": "package ghanageo_test\n\nimport (\n\t\"context\"\n\t\"fmt\"\n\t\"log\"\n\n\tghanageo \"github.com/ghanageo/ghanageo-go\"\n)\n\nfunc ExampleClient_Regions() {\n\tclient, err := ghanageo.New()\n\tif err != nil {\n\t\tlog.Fatal(err)\n\t}\n\t_ = client\n\t// Network calls take context.Context first and are anonymous by default.\n\t// page, err := client.Regions(context.Background(), ghanageo.PageOptions{Limit: 16})\n\tfmt.Println(ghanageo.APIVersion)\n\t// Output: v1\n\t_ = context.Background()\n}"
  },
  {
    "id": "dart",
    "label": "Dart",
    "source": "sdks/dart/example/regions.dart",
    "install": "dart pub add ghanageo",
    "runtime": "Dart 3.5+",
    "protocols": [
      "REST"
    ],
    "cancellation": "CancellationToken",
    "retry": "RetryPolicy; max five",
    "pagination": "Stream<Page<T>>",
    "errors": "GhanaGeoException",
    "code": "import 'package:ghanageo/ghanageo.dart';\n\nFuture<void> main() async {\n  final client = GhanaGeoClient();\n  try {\n    final page = await client.regions(limit: 16);\n    for (final region in page.data) {\n      print('${region.name}: ${region.capital}');\n    }\n  } finally {\n    client.close();\n  }\n}"
  },
  {
    "id": "java",
    "label": "Java",
    "source": "sdks/java/examples/src/main/java/dev/ghanageo/examples/SearchExample.java",
    "install": "implementation(\"dev.ghanageo:ghanageo-java:2.0.0\")",
    "runtime": "Java 21+",
    "protocols": [
      "REST"
    ],
    "cancellation": "CancellationToken / CompletableFuture",
    "retry": "Builder retry policy; max five",
    "pagination": "Flow.Publisher<Page<T>>",
    "errors": "GhanaGeoException",
    "code": "package dev.ghanageo.examples;\nimport dev.ghanageo.GhanaGeoClient;\nimport java.util.Map;\npublic final class SearchExample { private SearchExample(){} public static void main(String[]args){try(var client=GhanaGeoClient.create()){client.search(\"Kumasi\",Map.of(\"limit\",5)).data().forEach(hit->System.out.println(hit.name()));}} }"
  },
  {
    "id": "dotnet",
    "label": "C# / .NET",
    "source": "sdks/dotnet/examples/ConsoleExample/Program.cs",
    "install": "dotnet add package GhanaGeo",
    "runtime": ".NET 8+",
    "protocols": [
      "REST"
    ],
    "cancellation": "CancellationToken",
    "retry": "Options retry policy; max five",
    "pagination": "IAsyncEnumerable<Page<T>>",
    "errors": "GhanaGeoException",
    "code": "using GhanaGeo;\n\nusing var http = new HttpClient();\nvar client = new GhanaGeoClient(http); // Public reads are anonymous by default.\nawait foreach (var page in client.EnumerateRegionPagesAsync(new ListOptions(Limit: 5)))\n{\n    foreach (var region in page.Data) Console.WriteLine($\"{region.Name} ({region.Id})\");\n}"
  },
  {
    "id": "php",
    "label": "PHP",
    "source": "sdks/php/examples/regions.php",
    "install": "composer require ghanageo/ghanageo-php",
    "runtime": "PHP 8.2+",
    "protocols": [
      "REST"
    ],
    "cancellation": "RequestOptions deadline/token",
    "retry": "RetryPolicy; max five",
    "pagination": "Generator<Page>",
    "errors": "GhanaGeoException",
    "code": "<?php\n\ndeclare(strict_types=1);\n\nuse GhanaGeo\\Client;\nuse GuzzleHttp\\Client as GuzzleClient;\nuse GuzzleHttp\\Psr7\\HttpFactory;\n\nrequire dirname(__DIR__).'/vendor/autoload.php';\n\n$factory = new HttpFactory;\n$client = new Client(new GuzzleClient(['http_errors' => false, 'timeout' => 10]), $factory);\n\nforeach ($client->allRegions() as $region) {\n    echo $region->name.PHP_EOL;\n}"
  },
  {
    "id": "curl",
    "label": "curl",
    "source": "scripts/docs-sdk/examples/curl.sh",
    "install": "No install beyond curl",
    "runtime": "curl 8+",
    "protocols": [
      "REST"
    ],
    "cancellation": "Shell process signal / --max-time",
    "retry": "Explicit --retry for safe reads",
    "pagination": "Follow nextCursor explicitly",
    "errors": "HTTP status plus JSON error envelope",
    "code": "#!/usr/bin/env sh\nset -eu\n\ncurl --fail --silent --show-error \\\n  \"${GHANAGEO_API_URL:-https://api-geo.digitalghana.dev}/v1/search?q=Kumasi&limit=5\""
  }
] as const;
