#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"
require "yaml"

ROOT = File.expand_path("../..", __dir__)
OPENAPI_PATH = File.join(ROOT, "contracts/openapi/v1.yaml")
PROTO_PATH = File.join(ROOT, "proto/ghanageo/v1/geography.proto")
GRAPHQL_PATH = File.join(ROOT, "contracts/graphql/schema.graphql")
OUTPUT_PATH = File.join(ROOT, "contracts/conformance/operations.generated.yaml")
PUBLIC_TAGS = %w[Geography Spatial Datasets].freeze
GRAPHQL_MAPPING = {
  "listRegions" => "Query.regions", "getRegion" => "Query.region",
  "listRegionDistricts" => "Region.districts", "listDistricts" => "Query.districts",
  "getDistrict" => "Query.district", "listDistrictPlaces" => "District.places",
  "listPlaces" => "Query.places", "getPlace" => "Query.place",
  "search" => "Query.search", "autocomplete" => "Query.autocomplete",
  "geocode" => "Query.geocode", "reverseGeocode" => "Query.reverse",
  "nearby" => "Query.nearby", "getBoundary" => "Region.boundary",
  "listDatasets" => "Query.datasetVersions"
}.freeze

options = { check: false }
OptionParser.new do |parser|
  parser.on("--check", "Fail when generated inventory differs from disk") { options[:check] = true }
end.parse!

# The checked-in OpenAPI contract is trusted repository input and uses YAML
# anchors to keep repeated response maps identical. Psych disables aliases by
# default, so allow them explicitly while retaining safe_load's class limits.
openapi = YAML.safe_load(File.read(OPENAPI_PATH), [], [], true)
rpc_names = File.read(PROTO_PATH).scan(/^\s*rpc\s+(\w+)\s*\(/).flatten
abort "duplicate protobuf RPC names are ambiguous" unless rpc_names.uniq.length == rpc_names.length
graphql_fields = {}
current_type = nil
File.readlines(GRAPHQL_PATH).each do |line|
  type_match = line.match(/^type\s+(\w+)\s*\{/)
  current_type = type_match[1] if type_match
  current_type = nil if current_type && line.match?(/^\}/)
  field_match = line.match(/^\s{2}(\w+)(?:\([^)]*\))?\s*:/)
  next unless current_type && field_match

  qualified_field = "#{current_type}.#{field_match[1]}"
  abort "duplicate GraphQL field #{qualified_field} is ambiguous" if graphql_fields[qualified_field]
  graphql_fields[qualified_field] = true
end

resolve_ref = lambda do |value|
  next value unless value.is_a?(Hash) && value["$ref"]

  value["$ref"].delete_prefix("#/").split("/").reduce(openapi) { |node, segment| node.fetch(segment) }
end

operations = openapi.fetch("paths").each_with_object([]) do |(path, path_item), entries|
  path_item.each do |method, operation|
    next unless %w[get post put patch delete].include?(method)
    next unless (Array(operation["tags"]) & PUBLIC_TAGS).any?

    operation_id = operation.fetch("operationId")
    rpc = rpc_names.find { |name| name.downcase == operation_id.downcase }
    graphql = GRAPHQL_MAPPING[operation_id]
    abort "GraphQL mapping #{graphql} for #{operation_id} is absent from the SDL" if graphql && !graphql_fields[graphql]
    successes = operation.fetch("responses").select { |status, _| status.to_s.match?(/^2\d\d$/) }
    abort "#{operation_id} must have exactly one 2xx response; found #{successes.keys.join(", ")}" unless successes.length == 1
    success = successes.first
    success_status, success_response = success
    success_response = resolve_ref.call(success_response)
    content = success_response.is_a?(Hash) ? success_response.fetch("content", {}) : {}
    media_type, media = content.find { |_type, value| value.is_a?(Hash) && value["schema"] }
    schema_ref = media&.dig("schema", "$ref")

    entries << {
      "operation" => operation_id,
      "rest" => { "method" => method.upcase, "path" => path, "successStatus" => success_status.to_i },
      "grpc" => rpc,
      "graphql" => graphql && { "field" => graphql },
      "response" => {
        "mediaType" => media_type || "application/octet-stream",
        "schema" => schema_ref&.split("/")&.last || "Binary"
      }
    }.reject { |_key, value| value.nil? }
  end
end

operation_ids = operations.map { |entry| entry.fetch("operation") }
abort "duplicate OpenAPI operationId is ambiguous" unless operation_ids.uniq.length == operation_ids.length

represented_rpcs = operations.map { |entry| entry["grpc"] }.compact
(rpc_names - represented_rpcs).each do |rpc|
  operation_id = rpc.sub(/\A./) { |character| character.downcase }
  operations << {
    "operation" => operation_id,
    "grpc" => rpc,
    "response" => { "mediaType" => "application/protobuf", "schema" => "#{rpc}Response" }
  }
end
operations.sort_by! { |entry| entry.fetch("operation") }

document = {
  "version" => 1,
  "generatedFrom" => ["contracts/openapi/v1.yaml", "proto/ghanageo/v1/geography.proto", "contracts/graphql/schema.graphql"],
  "operations" => operations
}
rendered = "# Generated by tools/conformance/generate.rb. Do not edit.\n" + YAML.dump(document)

if options[:check]
  abort "conformance operation inventory is stale; run ruby tools/conformance/generate.rb" unless File.exist?(OUTPUT_PATH) && File.read(OUTPUT_PATH) == rendered
else
  File.write(OUTPUT_PATH, rendered)
  puts "wrote #{OUTPUT_PATH.sub(ROOT + "/", "")} (#{operations.length} operations)"
end
