// Code generated by cmd/gencontracts from contracts/errors/catalog.yaml. DO NOT EDIT.

export const GHANAGEO_ERROR_CODES = [
  "DEADLINE_EXCEEDED",
  "INTERNAL",
  "INVALID_ARGUMENT",
  "INVALID_COORDINATES",
  "KEY_REVOKED",
  "NOT_FOUND",
  "ORIGIN_NOT_ALLOWED",
  "PAYLOAD_TOO_LARGE",
  "PERMISSION_DENIED",
  "QUERY_TOO_COMPLEX",
  "QUERY_TOO_SHORT",
  "QUOTA_EXCEEDED",
  "RADIUS_OUT_OF_RANGE",
  "RATE_LIMIT_EXCEEDED",
  "RESOURCE_GONE",
  "UNAUTHENTICATED",
] as const;

export type GhanaGeoErrorCode = (typeof GHANAGEO_ERROR_CODES)[number];

export interface ErrorCatalogEntry {
  readonly http: number;
  readonly grpc: string;
  readonly message: string;
  readonly details: readonly string[];
}

export const ERROR_CATALOG: Record<GhanaGeoErrorCode, ErrorCatalogEntry> = {
  DEADLINE_EXCEEDED: { http: 504, grpc: "DEADLINE_EXCEEDED", message: "The request took too long and was cancelled.", details: [] },
  INTERNAL: { http: 500, grpc: "INTERNAL", message: "An unexpected error occurred.", details: [] },
  INVALID_ARGUMENT: { http: 400, grpc: "INVALID_ARGUMENT", message: "A request parameter was malformed or missing.", details: [] },
  INVALID_COORDINATES: { http: 400, grpc: "INVALID_ARGUMENT", message: "Coordinates are out of range.", details: ["latitude", "longitude"] },
  KEY_REVOKED: { http: 401, grpc: "UNAUTHENTICATED", message: "This API key is no longer valid.", details: [] },
  NOT_FOUND: { http: 404, grpc: "NOT_FOUND", message: "No record matches that identifier.", details: ["id"] },
  ORIGIN_NOT_ALLOWED: { http: 403, grpc: "PERMISSION_DENIED", message: "This origin is not on the key's allow-list.", details: ["origin"] },
  PAYLOAD_TOO_LARGE: { http: 413, grpc: "RESOURCE_EXHAUSTED", message: "The request body is too large.", details: [] },
  PERMISSION_DENIED: { http: 403, grpc: "PERMISSION_DENIED", message: "This key lacks the required scope.", details: ["requiredScope"] },
  QUERY_TOO_COMPLEX: { http: 400, grpc: "INVALID_ARGUMENT", message: "The GraphQL query exceeds the complexity budget.", details: ["cost", "maxCost", "depth", "maxDepth"] },
  QUERY_TOO_SHORT: { http: 400, grpc: "INVALID_ARGUMENT", message: "The search query is too short.", details: ["minLength"] },
  QUOTA_EXCEEDED: { http: 429, grpc: "RESOURCE_EXHAUSTED", message: "The monthly quota for this plan is exhausted.", details: ["resetsAt"] },
  RADIUS_OUT_OF_RANGE: { http: 400, grpc: "INVALID_ARGUMENT", message: "Radius exceeds the maximum.", details: ["maxRadiusMeters"] },
  RATE_LIMIT_EXCEEDED: { http: 429, grpc: "RESOURCE_EXHAUSTED", message: "Request rate exceeded.", details: ["retryAfterSeconds", "limit"] },
  RESOURCE_GONE: { http: 410, grpc: "NOT_FOUND", message: "This record was merged into another.", details: ["mergedInto", "reason"] },
  UNAUTHENTICATED: { http: 401, grpc: "UNAUTHENTICATED", message: "No valid credential was supplied.", details: [] },
};
