/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ghana's regions
         * @description Returns the 16 regions. Cost class **cheap** (1 unit).
         */
        get: operations["listRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one region */
        get: operations["getRegion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/{id}/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List districts in a region
         * @description Returns `404` for an unknown region rather than an empty list, so a
         *     typo is distinguishable from a genuinely empty region.
         */
        get: operations["listRegionDistricts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and filter districts (MMDAs) */
        get: operations["listDistricts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/districts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one district */
        get: operations["getDistrict"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/districts/{id}/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List places in a district */
        get: operations["listDistrictPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and filter places */
        get: operations["listPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve a place
         * @description A merged or deprecated identifier returns `410` with
         *     `error.details.mergedInto`, so stored ids keep resolving.
         */
        get: operations["getPlace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full and fuzzy location search
         * @description Typo-tolerant search across names and aliases. Every result carries a
         *     confidence score and a match explanation. Ambiguous queries return
         *     multiple candidates rather than a guess. Cost class **normal** (2).
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Low-latency typeahead suggestions
         * @description Target p95 under 200 ms. Cost class **normal** (2).
         */
        get: operations["autocomplete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Text to ranked geographic candidates */
        get: operations["geocode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coordinates to containing geography
         * @description Returns the containing region and district plus nearby localities.
         *     Coordinates outside Ghana return an empty result, not an error.
         *     Cost class **spatial** (4).
         */
        get: operations["reverseGeocode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spatial proximity search
         * @description Cost class **spatial** (4).
         */
        get: operations["nearby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boundaries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GeoJSON boundary for a region, district or place
         * @description Cost class **geometry** (5–10, by vertex count).
         */
        get: operations["getBoundary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Published dataset versions */
        get: operations["listDatasets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{version}/downloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bulk download metadata for a dataset version */
        get: operations["listDatasetDownloads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List OpenStreetMap-derived roads */
        get: operations["listRoads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pois": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List OpenStreetMap-derived points of interest */
        get: operations["listPointsOfInterest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{version}/downloads/{entity}.{format}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream one published dataset artifact */
        get: operations["downloadDatasetArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a developer account */
        post: operations["registerAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify an account email address */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a browser session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete login with a TOTP code */
        post: operations["completeTotpChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete login with a single-use recovery code */
        post: operations["completeRecoveryChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/enrol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enrol TOTP for the current account */
        post: operations["enrolTotp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke every account session */
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current account session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active account sessions */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkeys/register/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin passkey registration */
        post: operations["beginPasskeyRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkeys/register/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish passkey registration */
        post: operations["finishPasskeyRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkeys/login/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin passkey login */
        post: operations["beginPasskeyLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkeys/login/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish passkey login */
        post: operations["finishPasskeyLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered passkeys */
        get: operations["listPasskeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkeys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a registered passkey */
        delete: operations["deletePasskey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/developer/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations for the current member */
        get: operations["listDeveloperOrganizations"];
        put?: never;
        /** Create an organization */
        post: operations["createDeveloperOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/developer/organizations/{orgId}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organization invitations */
        get: operations["listOrganizationInvitations"];
        put?: never;
        /** Invite an organization member */
        post: operations["inviteOrganizationMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/developer/organizations/{orgId}/invitations/{inviteId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a pending invitation */
        post: operations["revokeOrganizationInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/developer/organizations/{orgId}/transfer-ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transfer organization ownership */
        post: operations["transferOrganizationOwnership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/developer/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an organization invitation */
        post: operations["acceptOrganizationInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/developer/organizations/{orgId}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organization applications */
        get: operations["listDeveloperApplications"];
        put?: never;
        /** Create an application */
        post: operations["createDeveloperApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/developer/organizations/{orgId}/applications/{appId}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List application API keys */
        get: operations["listApplicationKeys"];
        put?: never;
        /** Create an API key; its secret is returned once */
        post: operations["createApplicationKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/developer/organizations/{orgId}/applications/{appId}/keys/{keyId}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate an API key and return the new secret once */
        post: operations["rotateApplicationKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/developer/organizations/{orgId}/applications/{appId}/keys/{keyId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke an API key immediately */
        post: operations["revokeApplicationKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/developer/organizations/{orgId}/applications/{appId}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read attributed application usage */
        get: operations["getApplicationUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/developer/organizations/{orgId}/applications/{appId}/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Page through secret-free application request logs */
        get: operations["listApplicationRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read effective steward permissions */
        get: operations["getAdminPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/regions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a region as an authorized steward */
        patch: operations["updateAdminRegion"];
        trace?: never;
    };
    "/admin/districts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a district as an authorized steward */
        patch: operations["updateAdminDistrict"];
        trace?: never;
    };
    "/admin/places/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a place as an authorized steward */
        patch: operations["updateAdminPlace"];
        trace?: never;
    };
    "/admin/places/{id}/deprecate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deprecate a place into a resolvable redirect */
        post: operations["deprecateAdminPlace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JsonObject: {
            [key: string]: unknown;
        };
        Error: {
            error: {
                /**
                 * @description A stable machine code from contracts/errors/catalog.yaml.
                 * @enum {string}
                 */
                code: "INVALID_ARGUMENT" | "INVALID_COORDINATES" | "RADIUS_OUT_OF_RANGE" | "QUERY_TOO_SHORT" | "PAYLOAD_TOO_LARGE" | "UNAUTHENTICATED" | "KEY_REVOKED" | "PERMISSION_DENIED" | "ORIGIN_NOT_ALLOWED" | "NOT_FOUND" | "RESOURCE_GONE" | "RATE_LIMIT_EXCEEDED" | "QUOTA_EXCEEDED" | "QUERY_TOO_COMPLEX" | "DEADLINE_EXCEEDED" | "INTERNAL";
                message: string;
                /** @description Quote this when contacting support. */
                requestId: string;
                details?: {
                    [key: string]: unknown;
                };
                /** Format: uri-reference */
                docs: string;
            };
        };
        Coordinate: {
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
        };
        Ref: {
            id: string;
            name: string;
        };
        /** @description Where this record came from. A record without provenance cannot be published. */
        Provenance: {
            sourceId: string;
            /** Format: uri */
            sourceUrl?: string;
            retrievedAt?: string;
        };
        /** @enum {string} */
        Status: "ACTIVE" | "DEPRECATED" | "MERGED";
        /**
         * @description How far a record has moved toward canonical truth.
         *     `SEED_NEEDS_CANONICAL_RECONCILIATION` rows are bootstrap data awaiting
         *     official GNHR/GSS reconciliation and are never auto-promoted.
         * @enum {string}
         */
        VerificationStatus: "REFERENCE" | "SEED_NEEDS_CANONICAL_RECONCILIATION" | "REVIEWED" | "CANONICAL";
        /** @enum {string} */
        PlaceType: "CITY" | "TOWN" | "VILLAGE" | "COMMUNITY" | "SUBURB" | "NEIGHBOURHOOD" | "HAMLET" | "SETTLEMENT" | "LOCALITY" | "REGIONAL_CAPITAL";
        Region: {
            id: string;
            /** @example GH */
            countryCode: string;
            name: string;
            capital?: string;
            /** @description Official code where reconciled. */
            code?: string;
            status: components["schemas"]["Status"];
            verificationStatus: components["schemas"]["VerificationStatus"];
            centroid?: components["schemas"]["Coordinate"];
            provenance: components["schemas"]["Provenance"];
            datasetVersion: string;
        };
        District: {
            id: string;
            name: string;
            code?: string;
            /** @description Metropolitan, Municipal or District. */
            type?: string;
            capital?: string;
            region: components["schemas"]["Ref"];
            status: components["schemas"]["Status"];
            verificationStatus: components["schemas"]["VerificationStatus"];
            centroid?: components["schemas"]["Coordinate"];
            provenance: components["schemas"]["Provenance"];
            datasetVersion: string;
        };
        Alias: {
            /** @description Preserves the true orthography, including Twi, Ga and Ewe characters. */
            value: string;
            type?: string;
            /** @example tw */
            language?: string;
            isPreferred?: boolean;
        };
        Place: {
            id: string;
            name: string;
            /** @description Deterministic search token; folded for matching only. */
            normalizedName: string;
            type: components["schemas"]["PlaceType"];
            region?: components["schemas"]["Ref"];
            district?: components["schemas"]["Ref"];
            parentPlaceId?: string;
            aliases: components["schemas"]["Alias"][];
            centroid?: components["schemas"]["Coordinate"];
            /** Format: int64 */
            population?: number;
            status: components["schemas"]["Status"];
            verificationStatus: components["schemas"]["VerificationStatus"];
            provenance: components["schemas"]["Provenance"];
            datasetVersion: string;
        };
        SearchResult: components["schemas"]["Place"] & {
            /**
             * Format: double
             * @description Confidence, 0 to 1.
             */
            score?: number;
            /** @description Why this matched, e.g. "alias match: Osu RE". */
            matchReason?: string;
        };
        PageMeta: {
            nextCursor?: string;
            datasetVersion: string;
        };
        RegionPage: components["schemas"]["PageMeta"] & {
            data: components["schemas"]["Region"][];
        };
        DistrictPage: components["schemas"]["PageMeta"] & {
            data: components["schemas"]["District"][];
        };
        PlacePage: components["schemas"]["PageMeta"] & {
            data: components["schemas"]["Place"][];
        };
        SearchPage: components["schemas"]["PageMeta"] & {
            data: components["schemas"]["SearchResult"][];
        };
        ReverseResult: {
            region?: components["schemas"]["Ref"];
            district?: components["schemas"]["Ref"];
            nearby?: components["schemas"]["Place"][];
            datasetVersion: string;
        };
        BoundaryFeature: {
            /** @constant */
            type: "Feature";
            /** @description GeoJSON geometry in WGS84 (EPSG:4326). */
            geometry: {
                /** @enum {string} */
                type: "Point" | "LineString" | "Polygon" | "MultiPoint" | "MultiLineString" | "MultiPolygon";
                coordinates: unknown[];
            };
            properties: {
                id?: string;
                name?: string;
                datasetVersion?: string;
                /** @description Required for ODbL and CC BY derived geometry. */
                attribution?: string;
            };
        };
        DatasetVersion: {
            /** @example 2026.08.1 */
            version: string;
            /** @enum {string} */
            status: "draft" | "validation" | "review" | "approved" | "published" | "rolled_back";
            /** Format: date-time */
            publishedAt?: string;
            changelog?: string;
            checksum?: string;
        };
        DatasetPage: {
            data: components["schemas"]["DatasetVersion"][];
        };
        DownloadList: {
            version: string;
            downloads: {
                /** @enum {string} */
                format: "json" | "csv" | "geojson" | "parquet";
                /** Format: uri */
                url: string;
                /** Format: int64 */
                sizeBytes?: number;
                checksum: string;
                attribution?: string;
            }[];
        };
    };
    responses: {
        /** @description Successful operation. */
        Success: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["JsonObject"];
            };
        };
        /** @description The request was malformed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No record matches that identifier. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The record was merged; follow `error.details.mergedInto`. */
        Gone: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit or quota exceeded. */
        RateLimited: {
            headers: {
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No valid API key or browser session was supplied. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The authenticated actor lacks the required permission. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description The stable internal identifier (ULID). Human codes are alternate identifiers, never primary keys.
         * @example 01KDVDNA00N6BFFK8VF5K8YXPW
         */
        Id: string;
        OrgId: string;
        AppId: string;
        KeyId: string;
        /** @description Opaque cursor from a previous response's `nextCursor`. */
        Cursor: string;
        Limit: number;
        /**
         * @description The search text. Abbreviations and Ghanaian orthography are normalized.
         * @example tema comm 25
         */
        Query: string;
        Lat: number;
        Lng: number;
    };
    requestBodies: {
        JsonBody: {
            content: {
                "application/json": components["schemas"]["JsonObject"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRegions: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous response's `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of regions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionPage"];
                };
            };
            401: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    getRegion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The stable internal identifier (ULID). Human codes are alternate identifiers, never primary keys.
                 * @example 01KDVDNA00N6BFFK8VF5K8YXPW
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The region. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Region"];
                };
            };
            404: components["responses"]["NotFound"];
            410: components["responses"]["Gone"];
        };
    };
    listRegionDistricts: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous response's `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                /**
                 * @description The stable internal identifier (ULID). Human codes are alternate identifiers, never primary keys.
                 * @example 01KDVDNA00N6BFFK8VF5K8YXPW
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of districts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictPage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listDistricts: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous response's `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                /** @description Restrict to one region. */
                regionId?: string;
                /** @description Prefix match on the normalized name. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of districts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictPage"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getDistrict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The stable internal identifier (ULID). Human codes are alternate identifiers, never primary keys.
                 * @example 01KDVDNA00N6BFFK8VF5K8YXPW
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The district. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["District"];
                };
            };
            404: components["responses"]["NotFound"];
            410: components["responses"]["Gone"];
        };
    };
    listDistrictPlaces: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous response's `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                type?: components["schemas"]["PlaceType"];
            };
            header?: never;
            path: {
                /**
                 * @description The stable internal identifier (ULID). Human codes are alternate identifiers, never primary keys.
                 * @example 01KDVDNA00N6BFFK8VF5K8YXPW
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of places. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacePage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPlaces: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous response's `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                districtId?: string;
                regionId?: string;
                type?: components["schemas"]["PlaceType"];
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of places. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacePage"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The stable internal identifier (ULID). Human codes are alternate identifiers, never primary keys.
                 * @example 01KDVDNA00N6BFFK8VF5K8YXPW
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The place. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Place"];
                };
            };
            404: components["responses"]["NotFound"];
            410: components["responses"]["Gone"];
        };
    };
    search: {
        parameters: {
            query: {
                /**
                 * @description The search text. Abbreviations and Ghanaian orthography are normalized.
                 * @example tema comm 25
                 */
                q: components["parameters"]["Query"];
                limit?: components["parameters"]["Limit"];
                /** @description Bias ranking toward this region. */
                regionId?: string;
                districtId?: string;
                type?: components["schemas"]["PlaceType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked candidates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    autocomplete: {
        parameters: {
            query: {
                /**
                 * @description The search text. Abbreviations and Ghanaian orthography are normalized.
                 * @example tema comm 25
                 */
                q: components["parameters"]["Query"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Suggestions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    geocode: {
        parameters: {
            query: {
                /**
                 * @description The search text. Abbreviations and Ghanaian orthography are normalized.
                 * @example tema comm 25
                 */
                q: components["parameters"]["Query"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked candidates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    reverseGeocode: {
        parameters: {
            query: {
                lat: components["parameters"]["Lat"];
                lng: components["parameters"]["Lng"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Containing geography and nearby places. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReverseResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    nearby: {
        parameters: {
            query: {
                lat: components["parameters"]["Lat"];
                lng: components["parameters"]["Lng"];
                /** @description Radius in metres. */
                radius?: number;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nearby places, nearest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacePage"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getBoundary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The stable internal identifier (ULID). Human codes are alternate identifiers, never primary keys.
                 * @example 01KDVDNA00N6BFFK8VF5K8YXPW
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A GeoJSON Feature. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/geo+json": components["schemas"]["BoundaryFeature"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listDatasets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published versions, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetPage"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listDatasetDownloads: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 2026.08.1 */
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available formats with checksums and attribution. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadList"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRoads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    listPointsOfInterest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    downloadDatasetArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
                entity: "regions" | "districts" | "places";
                format: "json" | "csv" | "geojson";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The immutable artifact bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    registerAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            201: components["responses"]["Success"];
            400: components["responses"]["BadRequest"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            200: components["responses"]["Success"];
            400: components["responses"]["BadRequest"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    completeTotpChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    completeRecoveryChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    enrolTotp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    beginPasskeyRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    finishPasskeyRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            200: components["responses"]["Success"];
            400: components["responses"]["BadRequest"];
        };
    };
    beginPasskeyLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            200: components["responses"]["Success"];
            400: components["responses"]["BadRequest"];
        };
    };
    finishPasskeyLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    listPasskeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    deletePasskey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The stable internal identifier (ULID). Human codes are alternate identifiers, never primary keys.
                 * @example 01KDVDNA00N6BFFK8VF5K8YXPW
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Passkey removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listDeveloperOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    createDeveloperOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            201: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    listOrganizationInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    inviteOrganizationMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            201: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    revokeOrganizationInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitation revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    transferOrganizationOwnership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    acceptOrganizationInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    listDeveloperApplications: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    createDeveloperApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            201: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    listApplicationKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                appId: components["parameters"]["AppId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    createApplicationKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                appId: components["parameters"]["AppId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            201: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    rotateApplicationKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                appId: components["parameters"]["AppId"];
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    revokeApplicationKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                appId: components["parameters"]["AppId"];
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getApplicationUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                appId: components["parameters"]["AppId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    listApplicationRequests: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous response's `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                orgId: components["parameters"]["OrgId"];
                appId: components["parameters"]["AppId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    getAdminPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    updateAdminRegion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The stable internal identifier (ULID). Human codes are alternate identifiers, never primary keys.
                 * @example 01KDVDNA00N6BFFK8VF5K8YXPW
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            200: components["responses"]["Success"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateAdminDistrict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The stable internal identifier (ULID). Human codes are alternate identifiers, never primary keys.
                 * @example 01KDVDNA00N6BFFK8VF5K8YXPW
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            200: components["responses"]["Success"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateAdminPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The stable internal identifier (ULID). Human codes are alternate identifiers, never primary keys.
                 * @example 01KDVDNA00N6BFFK8VF5K8YXPW
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            200: components["responses"]["Success"];
            403: components["responses"]["Forbidden"];
        };
    };
    deprecateAdminPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The stable internal identifier (ULID). Human codes are alternate identifiers, never primary keys.
                 * @example 01KDVDNA00N6BFFK8VF5K8YXPW
                 */
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonBody"];
        responses: {
            200: components["responses"]["Success"];
            403: components["responses"]["Forbidden"];
        };
    };
}
