package grpc

import (
	"reflect"
	"runtime"
	"strings"
	"testing"

	pb "github.com/ghanageo/ghanageo/services/api/gen/ghanageo/v1"
)

// Every RPC in the published contract must have a real handler on *Server.
//
// Embedding UnimplementedGeographyServiceServer is required for forward
// compatibility, but it also means a missing method COMPILES — the embedded
// stub silently answers UNIMPLEMENTED. A contract we publish and then fail to
// serve is worse than one we never published, so this asserts each method is
// declared on *Server itself rather than inherited from the stub.
//
// StreamDatasetChanges is the one deliberate exception: it is implemented, and
// returns UNIMPLEMENTED explicitly with the story that will build it, which is
// honest rather than accidental.
func TestEveryRPCHasAHandler(t *testing.T) {
	svcType := reflect.TypeOf(&Server{})

	desc := pb.GeographyService_ServiceDesc
	if len(desc.Methods)+len(desc.Streams) == 0 {
		t.Fatal("service descriptor has no methods — generation is broken")
	}

	// A promoted method from the embedded stub is indistinguishable from a
	// real one by name, signature OR func pointer: Go synthesises a wrapper
	// for it, and that wrapper even reports the same qualified name as a real
	// method. The one thing that gives it away is its source position, which
	// for a compiler-generated wrapper is "<autogenerated>" rather than a file
	// in this package. Anything reporting that is inherited, not implemented.
	check := func(name string) {
		t.Helper()
		m, ok := svcType.MethodByName(name)
		if !ok {
			t.Errorf("RPC %s has no handler at all", name)
			return
		}
		file, _ := runtime.FuncForPC(m.Func.Pointer()).FileLine(m.Func.Pointer())
		if file == "<autogenerated>" || strings.HasSuffix(file, "_grpc.pb.go") {
			t.Errorf("RPC %s resolves to the Unimplemented stub (declared at %q) — "+
				"the contract is published but not served", name, file)
		}
	}

	for _, m := range desc.Methods {
		check(m.MethodName)
	}
	for _, s := range desc.Streams {
		check(s.StreamName)
	}
}

// The service name in the descriptor must match the published package. A
// rename would break every existing client silently at dial time.
func TestServiceNameIsStable(t *testing.T) {
	const want = "ghanageo.v1.GeographyService"
	if got := pb.GeographyService_ServiceDesc.ServiceName; got != want {
		t.Errorf("service name changed: got %q, want %q", got, want)
	}
	if !strings.HasPrefix(want, "ghanageo.v1.") {
		t.Error("breaking changes belong in ghanageo.v2, never in place")
	}
}
