package dev.ghanageo.conformance;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import dev.ghanageo.GhanaGeoClient;
import dev.ghanageo.GhanaGeoException;
import dev.ghanageo.Version;
import dev.ghanageo.Models;
import dev.ghanageo.CancellationToken;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CancellationException;

/** Executes every REST-applicable contract case through the public Java facade. */
public final class ConformanceRunner {
  private static final ObjectMapper JSON = new ObjectMapper();
  public static void main(String[] args) throws Exception {
    if(args.length!=3) throw new IllegalArgumentException("usage: ConformanceRunner <exported-cases.json> <fixture-base-url> <report.json>");
    JsonNode contract=JSON.readTree(Path.of(args[0]).toFile()); String base=args[1]; ArrayNode results=JSON.createArrayNode(), evidence=JSON.createArrayNode(); String dataset="fixture"; int passed=0,failed=0;
    for(JsonNode c:contract.path("cases")) {
      if(!contains(c.path("protocols"),"rest")) continue;
      String id=c.path("id").asText(); String operation=c.path("operation").asText(); JsonNode input=c.path("input"); JsonNode expected=c.path("expect"); boolean ok=false; JsonNode response=null; String failureMessage=null;List<Models.WireEvidence> wire=new ArrayList<>();
      GhanaGeoClient.Builder builder=GhanaGeoClient.builder().baseUrl(base).maxRetries(0).defaultHeader("x-conformance-case",id).wireObserver(wire::add);
      String auth=input.path("auth").asText();if(!auth.isBlank()&&!auth.equals("omitted"))builder.apiKey(auth);
      try(var client=builder.build()) {
        try {
          if(id.equals("semantic.cancellation-propagates")){try(var source=CancellationToken.source()){var f=client.searchAsync("Kumasi",Map.of(),source.token());Thread.sleep(input.path("cancelAfterMilliseconds").asLong(10));source.cancel();try{f.join();ok=false;}catch(RuntimeException cancellation){ok=source.token().isCancelled()&&isCancellation(cancellation);}response=JSON.createObjectNode().put("cancelled",ok).put("tokenCancelled",source.token().isCancelled());}}
          else if(id.equals("semantic.cursor-pagination")){JsonNode first=JSON.valueToTree(client.places(Map.of("limit",2)));String cursor=first.path("nextCursor").asText();JsonNode second=JSON.valueToTree(client.places(Map.of("limit",2,"cursor",cursor)));ok=!cursor.isBlank()&&disjoint(first.path("data"),second.path("data"));response=first;}
          else { response=invoke(client,operation,input);ok=expected.path("outcome").asText().equals("success")&&validShape(response,expected.path("shape")); }
        } catch(GhanaGeoException e) {ObjectNode error=JSON.createObjectNode();error.put("status",e.status());error.put("code",e.code());error.put("message",e.getMessage());error.put("requestId",e.requestId());error.put("docs",e.docs());error.set("details",e.details());response=error;ok=validError(e,expected);}
        catch(Throwable t){failureMessage=t.getClass().getSimpleName()+": "+t.getMessage();response=JSON.createObjectNode().put("failure",failureMessage);}
      }
      if(response!=null&&response.path("datasetVersion").isTextual())dataset=response.path("datasetVersion").asText();
      ok=ok&&statusMatches(expected,wire)&&authMatches(input,wire)&&semantic(id,response,wire)&&(id.equals("semantic.cancellation-propagates")||quotaMatches(expected.path("quotaCost"),wire));
      ObjectNode result=results.addObject().put("caseId",id).put("status",ok?"passed":"failed");result.putArray("protocols").add("rest");if(!ok)result.put("message",failureMessage==null?"actual wire exchange did not satisfy status, shape, quota or semantic contract":failureMessage);
      JsonNode requests=JSON.valueToTree(wire.stream().filter(w->w.phase().equals("request")).toList());JsonNode responses=JSON.valueToTree(wire.stream().filter(w->w.phase().equals("response")).toList());ObjectNode ev=evidence.addObject().put("caseId",id).put("protocol","rest").put("requestDigest",digest(canonical(requests))).put("responseDigest",digest(canonical(responses)));
      if(ok)passed++;else failed++;
    }
    ObjectNode report=JSON.createObjectNode();report.put("schemaVersion",2);report.putObject("contract").put("digest",contract.path("contractDigest").asText()).put("runnerVersion","1.0.0");ObjectNode sdk=report.putObject("sdk");sdk.put("language","java").put("name","dev.ghanageo:ghanageo-java").put("version",Version.SDK);sdk.putArray("supportedProtocols").add("rest");report.put("apiVersion",Version.API).put("datasetVersion",dataset);report.putObject("summary").put("passed",passed).put("failed",failed).put("skipped",0);report.put("evidenceDigest",digest(canonical(evidence)));report.set("evidence",evidence);report.set("results",results);JSON.writerWithDefaultPrettyPrinter().writeValue(Path.of(args[2]).toFile(),report);if(failed>0)throw new IllegalStateException(failed+" conformance cases failed");
  }
  private static JsonNode invoke(GhanaGeoClient c,String op,JsonNode input)throws Exception {Map<String,Object> q=map(input.path("query"));JsonNode p=input.path("path");Object value=switch(op){case"listRegions"->c.regions(q);case"getRegion"->c.region(p.path("id").asText());case"listRegionDistricts"->c.regionDistricts(p.path("id").asText(),q);case"listDistricts"->c.districts(q);case"getDistrict"->c.district(p.path("id").asText());case"listDistrictPlaces"->c.districtPlaces(p.path("id").asText(),q);case"listPlaces"->c.places(q);case"getPlace"->c.place(p.path("id").asText());case"search"->c.search(q.getOrDefault("q","Kumasi").toString(),q);case"autocomplete"->c.autocomplete(q.get("q").toString(),number(q,"limit",10));case"geocode"->c.geocode(q.get("q").toString(),number(q,"limit",10));case"reverseGeocode"->c.reverseGeocode(decimal(q,"lat",0),decimal(q,"lng",0));case"nearby"->c.nearby(decimal(q,"lat",6.6885),decimal(q,"lng",-1.6244),number(q,"radius",5000),number(q,"limit",20));case"getBoundary"->c.boundary(p.path("id").asText());case"listDatasets"->c.datasets();case"listDatasetDownloads"->c.datasetDownloads(p.path("version").asText());case"downloadDatasetArtifact"->{Path tmp=Files.createTempFile("ghanageo-conformance-",".bin");try{c.downloadDatasetArtifact(p.path("version").asText(),p.path("entity").asText(),p.path("format").asText(),tmp,java.util.Optional.empty());yield JSON.createObjectNode().put("bytes",Files.size(tmp));}finally{Files.deleteIfExists(tmp);}}case"listRoads"->c.roads();case"listPointsOfInterest"->c.pointsOfInterest();default->throw new IllegalArgumentException("missing operation "+op);};return JSON.valueToTree(value);}
  private static Map<String,Object> map(JsonNode node){Map<String,Object> r=new LinkedHashMap<>();node.fields().forEachRemaining(e->{JsonNode v=e.getValue();r.put(e.getKey(),v.isNumber()?v.numberValue():v.isBoolean()?v.booleanValue():v.asText());});return r;} private static int number(Map<String,Object>m,String k,int d){return m.containsKey(k)?Integer.parseInt(m.get(k).toString()):d;}private static double decimal(Map<String,Object>m,String k,double d){return m.containsKey(k)?Double.parseDouble(m.get(k).toString()):d;}
  private static boolean contains(JsonNode a,String v){for(JsonNode n:a)if(n.asText().equals(v))return true;return false;}private static boolean requiredPresent(JsonNode n,JsonNode fields){for(JsonNode f:fields)if(n.at("/"+f.asText().replace(".","/")).isMissingNode()||n.at("/"+f.asText().replace(".","/")).isNull())return false;return true;}private static boolean validShape(JsonNode n,JsonNode shape){String type=shape.path("type").asText();return (type.equals("binary")||type.equals("object")&&n.isObject()||type.equals("array")&&n.isArray())&&requiredPresent(n,shape.path("required"));}private static boolean validError(GhanaGeoException e,JsonNode expected){if(!expected.path("outcome").asText().equals("error")||e.status()!=expected.path("httpStatus").asInt()||!expected.path("error").path("code").asText().equals(e.code()))return false;for(JsonNode f:expected.path("error").path("requiredFields")){String k=f.asText();boolean present=switch(k){case"code"->e.code()!=null;case"message"->e.getMessage()!=null;case"requestId"->e.requestId()!=null;case"docs"->e.docs()!=null;default->k.startsWith("details.")&&e.details()!=null&&!e.details().path(k.substring(8)).isMissingNode();};if(!present)return false;}return true;}private static boolean disjoint(JsonNode a,JsonNode b){java.util.Set<String>s=new java.util.HashSet<>();a.forEach(x->s.add(x.path("id").asText()));for(JsonNode x:b)if(s.contains(x.path("id").asText()))return false;return true;}
  private static boolean semantic(String id,JsonNode response,List<Models.WireEvidence>wire){if(id.equals("semantic.anonymous-default"))return wire.stream().filter(w->w.phase().equals("request")).noneMatch(w->w.headers().containsKey("Authorization")||w.headers().containsKey("authorization"));if(id.equals("semantic.dataset-version-on-pages"))return !response.path("datasetVersion").asText().isBlank();if(id.equals("semantic.autocomplete-orthography"))return response.toString().contains("Mampɔŋ");if(id.equals("semantic.reverse-outside-ghana"))return response.path("nearby").isArray()&&response.path("nearby").isEmpty();if(id.equals("semantic.cancellation-propagates"))return response.path("cancelled").asBoolean()&&wire.stream().anyMatch(w->w.phase().equals("request"));return true;}
  private static boolean isCancellation(Throwable error){for(Throwable current=error;current!=null;current=current.getCause())if(current instanceof CancellationException)return true;return false;}
  private static boolean statusMatches(JsonNode expected,List<Models.WireEvidence>wire){if(!expected.has("httpStatus"))return true;return wire.stream().filter(w->w.phase().equals("response")).reduce((a,b)->b).map(w->w.status()!=null&&w.status()==expected.path("httpStatus").asInt()).orElse(false);}
  private static boolean authMatches(JsonNode input,List<Models.WireEvidence>wire){boolean sent=wire.stream().filter(w->w.phase().equals("request")).anyMatch(w->w.headers().keySet().stream().anyMatch(k->k.equalsIgnoreCase("authorization")));String expected=input.path("auth").asText();return expected.isBlank()||expected.equals("omitted")?!sent:sent;}
  private static boolean quotaMatches(JsonNode expected,List<Models.WireEvidence>wire){for(int i=wire.size()-1;i>=0;i--){Models.WireEvidence w=wire.get(i);if(!w.phase().equals("response"))continue;String raw=w.headers().entrySet().stream().filter(e->e.getKey().equalsIgnoreCase("x-conformance-quota")).flatMap(e->e.getValue().stream()).findFirst().orElse(null);if(raw==null)return false;try{JsonNode actual=JSON.readTree(raw);if(!actual.path("class").asText().equals(expected.path("class").asText()))return false;if(expected.has("units")&&actual.path("units").asInt(-1)!=expected.path("units").asInt())return false;if(expected.has("minimumUnits")&&actual.path("minimumUnits").asInt(-1)!=expected.path("minimumUnits").asInt())return false;if(expected.has("maximumUnits")&&actual.path("maximumUnits").asInt(-1)!=expected.path("maximumUnits").asInt())return false;return true;}catch(Exception invalid){return false;}}return false;}
  private static byte[] canonical(JsonNode n)throws Exception{if(n==null)return"null".getBytes(StandardCharsets.UTF_8);if(n.isObject()){ObjectNode sorted=JSON.createObjectNode();List<String>keys=new ArrayList<>();n.fieldNames().forEachRemaining(keys::add);keys.sort(Comparator.naturalOrder());for(String k:keys)sorted.set(k,JSON.readTree(canonical(n.get(k))));return JSON.writeValueAsBytes(sorted);}if(n.isArray()){ArrayNode a=JSON.createArrayNode();for(JsonNode x:n)a.add(JSON.readTree(canonical(x)));return JSON.writeValueAsBytes(a);}return JSON.writeValueAsBytes(n);}private static String digest(byte[] b)throws Exception{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}
}
