// Code generated by cmd/gencontracts from contracts/errors/catalog.yaml. DO NOT EDIT.

package apierr

// CatalogEntry is the published description of one error code.
type CatalogEntry struct {
	Code    Code
	HTTP    int
	GRPC    string
	Message string
	Details []string
}

// Catalog is every code in contracts/errors/catalog.yaml, keyed by code.
var Catalog = map[Code]CatalogEntry{
	DeadlineExceeded: {Code: DeadlineExceeded, HTTP: 504, GRPC: "DEADLINE_EXCEEDED", Message: "The request took too long and was cancelled.", Details: nil},
	Internal: {Code: Internal, HTTP: 500, GRPC: "INTERNAL", Message: "An unexpected error occurred.", Details: nil},
	InvalidArgument: {Code: InvalidArgument, HTTP: 400, GRPC: "INVALID_ARGUMENT", Message: "A request parameter was malformed or missing.", Details: nil},
	InvalidCoordinate: {Code: InvalidCoordinate, HTTP: 400, GRPC: "INVALID_ARGUMENT", Message: "Coordinates are out of range.", Details: []string{"latitude", "longitude"}},
	KeyRevoked: {Code: KeyRevoked, HTTP: 401, GRPC: "UNAUTHENTICATED", Message: "This API key is no longer valid.", Details: nil},
	NotFound: {Code: NotFound, HTTP: 404, GRPC: "NOT_FOUND", Message: "No record matches that identifier.", Details: []string{"id"}},
	OriginNotAllowed: {Code: OriginNotAllowed, HTTP: 403, GRPC: "PERMISSION_DENIED", Message: "This origin is not on the key's allow-list.", Details: []string{"origin"}},
	PayloadTooLarge: {Code: PayloadTooLarge, HTTP: 413, GRPC: "RESOURCE_EXHAUSTED", Message: "The request body is too large.", Details: nil},
	PermissionDenied: {Code: PermissionDenied, HTTP: 403, GRPC: "PERMISSION_DENIED", Message: "This key lacks the required scope.", Details: []string{"requiredScope"}},
	QueryTooComplex: {Code: QueryTooComplex, HTTP: 400, GRPC: "INVALID_ARGUMENT", Message: "The GraphQL query exceeds the complexity budget.", Details: []string{"cost", "maxCost", "depth", "maxDepth"}},
	QueryTooShort: {Code: QueryTooShort, HTTP: 400, GRPC: "INVALID_ARGUMENT", Message: "The search query is too short.", Details: []string{"minLength"}},
	QuotaExceeded: {Code: QuotaExceeded, HTTP: 429, GRPC: "RESOURCE_EXHAUSTED", Message: "The monthly quota for this plan is exhausted.", Details: []string{"resetsAt"}},
	RadiusOutOfRange: {Code: RadiusOutOfRange, HTTP: 400, GRPC: "INVALID_ARGUMENT", Message: "Radius exceeds the maximum.", Details: []string{"maxRadiusMeters"}},
	RateLimitExceeded: {Code: RateLimitExceeded, HTTP: 429, GRPC: "RESOURCE_EXHAUSTED", Message: "Request rate exceeded.", Details: []string{"retryAfterSeconds", "limit"}},
	ResourceGone: {Code: ResourceGone, HTTP: 410, GRPC: "NOT_FOUND", Message: "This record was merged into another.", Details: []string{"mergedInto", "reason"}},
	Unauthenticated: {Code: Unauthenticated, HTTP: 401, GRPC: "UNAUTHENTICATED", Message: "No valid credential was supplied.", Details: nil},
}
