package dev.ghanageo;

import com.sun.net.httpserver.HttpServer;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.concurrent.CancellationException;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.Flow;
import java.util.ArrayList;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

final class GhanaGeoClientTest {
  private HttpServer server;
  private String start(com.sun.net.httpserver.HttpHandler handler) throws Exception { server=HttpServer.create(new InetSocketAddress("127.0.0.1",0),0); server.createContext("/v1",handler); server.start(); return "http://127.0.0.1:"+server.getAddress().getPort()+"/v1"; }
  @AfterEach void stop(){if(server!=null)server.stop(0);}
  @Test void anonymousTypedRequestAndDatasetVersion() throws Exception { var auth=new java.util.concurrent.atomic.AtomicReference<String>(); String base=start(x->{auth.set(x.getRequestHeaders().getFirst("Authorization"));byte[] b="{\"data\":[],\"datasetVersion\":\"2026.08\"}".getBytes(StandardCharsets.UTF_8);x.sendResponseHeaders(200,b.length);x.getResponseBody().write(b);x.close();}); try(var client=GhanaGeoClient.builder().baseUrl(base).build()){assertEquals("2026.08",client.regions(Map.of("limit",2)).datasetVersion());assertNull(auth.get());} }
  @Test void errorsAreStructured() throws Exception {String base=start(x->{byte[] b="{\"error\":{\"code\":\"NOT_FOUND\",\"message\":\"missing\",\"requestId\":\"r1\",\"docs\":\"https://docs\",\"details\":{\"id\":\"x\"}}}".getBytes(StandardCharsets.UTF_8);x.sendResponseHeaders(404,b.length);x.getResponseBody().write(b);x.close();});try(var client=GhanaGeoClient.builder().baseUrl(base).build()){var e=assertThrows(GhanaGeoException.class,()->client.place("x"));assertEquals("NOT_FOUND",e.code());assertEquals("r1",e.requestId());assertEquals("x",e.details().path("id").asText());}}
  @Test void retriesOnlyBoundedSafeReads() throws Exception {AtomicInteger calls=new AtomicInteger();String base=start(x->{int s=calls.incrementAndGet()<3?503:200;byte[] b=(s==200?"{}":"{\"error\":{\"code\":\"INTERNAL\"}}").getBytes();x.sendResponseHeaders(s,b.length);x.getResponseBody().write(b);x.close();});try(var client=GhanaGeoClient.builder().baseUrl(base).retryDelay(java.time.Duration.ZERO).build()){client.datasets();assertEquals(3,calls.get());}}
  @Test void cancellationPropagatesToWireFuture() throws Exception {String base=start(x->{try{Thread.sleep(500);}catch(InterruptedException ignored){}byte[] b="{}".getBytes();x.sendResponseHeaders(200,b.length);x.getResponseBody().write(b);x.close();});try(var client=GhanaGeoClient.builder().baseUrl(base).build()){var future=client.searchAsync("Kumasi",Map.of());assertTrue(future.cancel(true));assertThrows(CancellationException.class,future::join);}}
  @Test void repeatedCursorFailsIterator() throws Exception {String base=start(x->{byte[] b="{\"data\":[],\"datasetVersion\":\"v\",\"nextCursor\":\"same\"}".getBytes();x.sendResponseHeaders(200,b.length);x.getResponseBody().write(b);x.close();});try(var client=GhanaGeoClient.builder().baseUrl(base).build()){var it=client.placePages(Map.of()).iterator();it.next();assertThrows(GhanaGeoException.class,it::hasNext);}}
  @Test void typedRecordsPreserveGhanaianOrthographyAndEnums() throws Exception {String base=start(x->{byte[]b="{\"data\":[{\"id\":\"p\",\"name\":\"Mampɔŋ\",\"normalizedName\":\"mampong\",\"type\":\"TOWN\",\"aliases\":[],\"status\":\"ACTIVE\",\"verificationStatus\":\"REFERENCE\",\"provenance\":{\"sourceId\":\"fixture\"},\"datasetVersion\":\"2026.08.3-ulid\"}],\"datasetVersion\":\"2026.08.3-ulid\"}".getBytes(StandardCharsets.UTF_8);x.sendResponseHeaders(200,b.length);x.getResponseBody().write(b);x.close();});try(var client=GhanaGeoClient.builder().baseUrl(base).build()){var page=client.autocomplete("Mamp",10);assertEquals("Mampɔŋ",page.data().getFirst().name());assertEquals(Models.PlaceType.TOWN,page.data().getFirst().type());assertEquals(Version.TESTED_DATASET,page.datasetVersion());}}
  @Test void tokenCancelsRetryDelayBeforeAnotherWireAttempt() throws Exception {AtomicInteger calls=new AtomicInteger();String base=start(x->{calls.incrementAndGet();byte[]b="{\"error\":{\"code\":\"INTERNAL\",\"message\":\"later\",\"requestId\":\"r\",\"docs\":\"/d\"}}".getBytes();x.getResponseHeaders().add("Retry-After","30");x.sendResponseHeaders(503,b.length);x.getResponseBody().write(b);x.close();});try(var source=CancellationToken.source();var client=GhanaGeoClient.builder().baseUrl(base).maxRetries(5).build()){var future=client.regionsAsync(Map.of(),source.token());while(calls.get()==0)Thread.onSpinWait();source.cancel();RuntimeException error=assertThrows(RuntimeException.class,future::join);assertTrue(error instanceof CancellationException||error.getCause() instanceof CancellationException);Thread.sleep(30);assertEquals(1,calls.get());}}
  @Test void chunkedJsonIsRejectedBeforeUnboundedBuffering() throws Exception {String base=start(x->{x.sendResponseHeaders(200,0);for(int i=0;i<32;i++)x.getResponseBody().write("xxxxxxxx".getBytes());x.close();});try(var client=GhanaGeoClient.builder().baseUrl(base).maxJsonBytes(32).maxRetries(0).build()){assertThrows(RuntimeException.class,()->client.regions(Map.of()));}}
  @Test void publisherIsLazyAndHonoursDemand() throws Exception {AtomicInteger calls=new AtomicInteger();String base=start(x->{int n=calls.incrementAndGet();String cursor=n==1?",\"nextCursor\":\"next\"":"";byte[]b=("{\"data\":[],\"datasetVersion\":\"v\""+cursor+"}").getBytes();x.sendResponseHeaders(200,b.length);x.getResponseBody().write(b);x.close();});try(var client=GhanaGeoClient.builder().baseUrl(base).build()){var pages=new ArrayList<Models.RegionPage>();var done=new CountDownLatch(1);class Subscriber implements Flow.Subscriber<Models.RegionPage>{Flow.Subscription subscription;public void onSubscribe(Flow.Subscription s){subscription=s;}public void onNext(Models.RegionPage p){pages.add(p);}public void onError(Throwable t){done.countDown();}public void onComplete(){done.countDown();}}var subscriber=new Subscriber();client.regionPagePublisher(Map.of(),CancellationToken.none()).subscribe(subscriber);assertEquals(0,calls.get());subscriber.subscription.request(1);while(pages.size()<1)Thread.onSpinWait();assertEquals(1,calls.get());subscriber.subscription.request(1);assertTrue(done.await(1,TimeUnit.SECONDS));assertEquals(2,calls.get());assertEquals(2,pages.size());}}
  @Test void asyncArtifactDownloadRetriesStreamsAndChecksDigest() throws Exception {AtomicInteger calls=new AtomicInteger();String base=start(x->{int status=calls.incrementAndGet()==1?503:200;byte[]body=(status==200?"ok":"later").getBytes();x.sendResponseHeaders(status,body.length);x.getResponseBody().write(body);x.close();});java.nio.file.Path target=java.nio.file.Files.createTempFile("ghanageo-java-test",".bin");try(var client=GhanaGeoClient.builder().baseUrl(base).retryDelay(java.time.Duration.ZERO).build()){var completed=client.downloadDatasetArtifactAsync("v","regions","json",target,java.util.Optional.of("2689367b205c16ce32ed4200942b8b8b1e262dfc70d9bc9fbc77c49699a4f1df"),CancellationToken.none()).join();assertEquals("ok",java.nio.file.Files.readString(completed));assertEquals(2,calls.get());}finally{java.nio.file.Files.deleteIfExists(target);}}
}
