/**
 * What every admin screen is for.
 *
 * GENERATED from agent_plan.md story acceptance criteria, then story ids were
 * verified to exist in the plan (a fabricated GEO-x.y rendered as a badge is
 * worse than no badge). Screens listed here that are not yet implemented render
 * via PlannedScreen: a route in the rail must land somewhere that explains
 * itself, never on a dead click or a 404.
 */

export interface ScreenSpec {
  title: string;
  story?: string | undefined;
  dependsOn?: string | undefined;
  purpose: string;
  capabilities: readonly string[];
}

export const SCREENS: Record<string, ScreenSpec> = {
  "/my-work": {
    title: "My Work",
    purpose: "Personalized dashboard showing pending work items assigned to the current user across all reviews and submissions.",
    capabilities: [
      "View pending change requests and community submissions assigned for your review",
      "Track district/place edits awaiting approval across all dataset versions",
      "Filter work items by status and submission date to prioritize action",
      "Navigate directly to affected regions, districts, or places from work queue",
      "Monitor import job reconciliation conflicts assigned to your stewardship",
      "See draft changes and evidence records requiring your moderation decision",
    ],
  },
  "/activity": {
    title: "Activity Feed",
    purpose: "System-wide activity feed showing recent administrative actions, dataset changes, and user submissions with audit trail.",
    capabilities: [
      "View timestamped audit trail of data operations by actor and timestamp",
      "Filter events by type: imports, releases, edits, submissions, approvals",
      "Navigate to specific regions, districts, or places from activity entries",
      "Search activity by dataset version, date range, or event type",
      "Export activity records for compliance documentation and security audits",
    ],
  },
  "/explorer": {
    title: "Location Explorer",
    story: "GEO-17.2",
    dependsOn: "GEO-14.5",
    purpose: "Map-first interface for browsing and filtering geographic places, districts, and regions.",
    capabilities: [
      "Browse regions/districts/places in hierarchy tree synchronized with map selection",
      "View GeoJSON boundary layers for regions and districts on Leaflet map",
      "Filter places by region, district, type, and verification status",
      "View detailed information panel for selected geography entries",
      "Deep-link to specific locations for sharing and preserving navigation state",
    ],
  },
  "/explorer/geometry": {
    title: "Geometry Workbench",
    story: "GEO-17.4",
    dependsOn: "GEO-17.2",
    purpose: "Draw, edit, and validate geographic polygon boundaries with shape integrity checks.",
    capabilities: [
      "Draw new polygons or edit existing region/district/place boundaries on map",
      "Validate polygons for self-intersections, coordinate ranges, containment violations",
      "Check geometries stay within Ghana bounding box before saving edits",
      "Receive explanatory errors that block save and prevent invalid data",
      "Visualize parent-child containment relationships during polygon editing",
    ],
  },
  "/explorer/coverage": {
    title: "Coverage Map",
    purpose: "Display data completeness and geographic coverage metrics across regions and sources.",
    capabilities: [
      "View coverage metrics showing data completeness by region and district",
      "Identify geographic areas with missing or incomplete place data",
      "See source coverage and geographic areas covered by each data source",
      "Filter coverage visualization by data type, source, and verification status",
      "Understand geographic features and places available for export",
    ],
  },
  "/geography/regions": {
    title: "Regions",
    story: "GEO-17.3",
    dependsOn: "GEO-17.1 admin shell & RBAC gating",
    purpose: "Create, edit, and deprecate Ghana's sixteen canonical regions with boundary geometry and provenance tracking.",
    capabilities: [
      "Create region with WGS84 geometry and official Ghana identifiers",
      "Edit region name, boundaries, and source provenance fields",
      "Deprecate region (creates place_redirects entry); audit trail recorded",
      "Search regions and filter by active/deprecated status",
      "Verify region contains expected child districts via spatial validation",
    ],
  },
  "/geography/districts": {
    title: "Districts / MMDAs",
    story: "GEO-17.3",
    dependsOn: "GEO-17.1 admin shell & RBAC gating",
    purpose: "Create, edit, and deprecate Ghana's 261 districts and MMDAs with region assignment and audit logging.",
    capabilities: [
      "Create MMDA district with name, geometry, and parent region",
      "Edit district boundaries, alternate names, and official GSS codes",
      "Deprecate district (creates redirect); view child places and audit trail",
      "Filter by region, status, and search by official district code",
      "View GSS/GNHR source data and dataset version linked to district",
    ],
  },
  "/geography/places": {
    title: "Places / Localities",
    story: "GEO-17.3",
    dependsOn: "GEO-17.1 admin shell & RBAC gating",
    purpose: "Create, edit, and deprecate places and localities with types, coordinates, and embedded name variants.",
    capabilities: [
      "Create place with type (city/town/village/settlement) and coordinates",
      "Edit place details, type, district/region link, and embedded aliases",
      "Deprecate place (creates redirect with mergedInto target) and audit",
      "Search places by name; filter by type, district, verification status",
      "View GeoNames/GNHR/OSM provenance and dataset version metadata",
    ],
  },
  "/geography/aliases": {
    title: "Aliases & Name Variants",
    story: "GEO-17.3",
    dependsOn: "GEO-17.1 admin shell & RBAC gating",
    purpose: "Manage alternative names and transliteration variants for places in Ghana's canonical geography.",
    capabilities: [
      "Add Twi/Ga/Ewe transliteration and alternate English name variants",
      "Edit alias normalization (case, punctuation, Ghanaian abbreviations)",
      "Link aliases to places and mark preferred or canonical names",
      "View which aliases are used in search indexes and relevance scoring",
      "Filter by language and verification_status (SEED/REVIEWED/CANONICAL)",
    ],
  },
  "/geography/roads": {
    title: "Roads",
    story: "GEO-17.3",
    dependsOn: "GEO-17.1 admin shell & RBAC gating",
    purpose: "Create, edit, and deprecate road network entries with geometry and geographic linkage.",
    capabilities: [
      "Create road with name, linestring geometry, and region/district link",
      "Edit road name, geometry, and OpenStreetMap attribution metadata",
      "Deprecate road (creates redirect) and view full audit trail",
      "Search roads by name; filter by district and verification status",
      "View road geometry on map and OSM source provenance",
    ],
  },
  "/geography/pois": {
    title: "Points of Interest",
    story: "GEO-17.3",
    dependsOn: "GEO-17.1 admin shell & RBAC gating",
    purpose: "Create, edit, and deprecate points of interest with types and district assignment.",
    capabilities: [
      "Create POI with type, location, district, and optional description",
      "Edit POI coordinates, type, district, and external source links",
      "Deprecate POI (creates redirect); record in audit trail",
      "Filter POIs by type, district, and search by name",
      "View POI source provenance (GeoNames/OSM) and dataset version",
    ],
  },
  "/geography/redirects": {
    title: "Merges & Redirects",
    story: "GEO-17.3",
    dependsOn: "GEO-17.1 admin shell & RBAC gating",
    purpose: "View and audit merged places and their redirect targets for deprecated record IDs.",
    capabilities: [
      "View place_redirects table: old_id, new_id, reason, merged_at timestamp",
      "See which places were merged as canonical duplicates after deduplication",
      "Filter by merge reason and date range for data reconciliation",
      "View immutable audit entries for all deprecations and merges",
      "Export redirect audit log for validation and downstream consumers",
    ],
  },
  "/ingest": {
    title: "Pipeline Overview",
    purpose: "Overview of all active and completed data ingestion runs with aggregate statistics.",
    capabilities: [
      "View summary statistics across all import pipelines by source and status",
      "Monitor queue depth, worker availability, and ETL freshness by source",
      "Filter runs by date, source, and outcome to find specific imports",
      "Access detailed error logs and reconciliation metrics for any run",
      "Trigger manual imports or pause running jobs when needed",
    ],
  },
  "/ingest/sources": {
    title: "Sources Register",
    story: "GEO-4.3",
    purpose: "Registry of data sources with metadata, update frequency, and acquisition status.",
    capabilities: [
      "Search and filter sources by region, type, and last-update timestamp",
      "View source metadata, provenance, and acquisition history with timestamps",
      "Inspect content-addressed payload hashes for reproducible imports",
      "Configure API credentials, endpoints, and fetch parameters per source",
      "Monitor last successful fetch and data freshness across all sources",
    ],
  },
  "/ingest/licences": {
    title: "Licences & Attribution",
    purpose: "Source licences and attribution requirements for regulatory compliance and publication.",
    capabilities: [
      "View all source licences (ODbL, CC BY, etc.) and attribution text",
      "Verify GhanaPostGPS licence gate compliance before publication",
      "Export attribution manifests for versioned datasets and downloads",
      "Check licence expiry dates and renewal status by source",
      "Ensure attribution appears in API responses and bulk exports",
    ],
  },
  "/ingest/connectors": {
    title: "Connectors & Adapters",
    story: "GEO-4.4",
    purpose: "Registered adapters for data source integration, configured endpoints and health.",
    capabilities: [
      "List adapter types (GNHR, GSS, OpenStreetMap, GeoNames) with status",
      "Configure fetch/validate/normalize pipeline stages for each adapter",
      "Run fixture tests without network calls to verify adapter logic",
      "View per-adapter error counts, logs, and reconciliation conflicts",
      "Enable or disable adapters per environment (local, staging, production)",
    ],
  },
  "/ingest/runs": {
    title: "Import Runs",
    story: "GEO-17.5",
    purpose: "Active and historical import runs with processed counts, errors, and outcomes.",
    capabilities: [
      "View import run status, duration, and counts of regions/districts/places processed",
      "Inspect error logs, validation failures, and reconciliation conflicts by run",
      "Review duplicate candidates flagged during matching and dedupe phases",
      "Access raw source record payloads and content-addressed hashes for audit",
      "Trigger manual re-import for failed or partial runs",
    ],
  },
  "/ingest/normalization": {
    title: "Normalization Rules",
    story: "GEO-5.1",
    purpose: "Configuration and testing of place-name normalization rules for Ghanaian geography.",
    capabilities: [
      "View normalization rules for Twi, Ga, Ewe diacritic folding and abbreviations",
      "Test place names through normalization pipeline (comm→community, Rd→road)",
      "Verify determinism: same input always yields identical normalized output",
      "Review and refine Ghanaian abbreviation expansions and special cases",
      "Export normalization golden-file test cases for CI validation",
    ],
  },
  "/ingest/duplicates": {
    title: "Duplicate Candidates",
    story: "GEO-5.2",
    dependsOn: "GEO-5.1",
    purpose: "Candidates detected as probable duplicates across sources with merge recommendations.",
    capabilities: [
      "Review duplicate candidates with geographic distance, name similarity, confidence scores",
      "Filter by region, district, source pairing, and confidence threshold",
      "View evidence linking candidates: coordinate proximity, parent district match",
      "Approve merges or request additional evidence before reconciliation",
      "Access evidence locker with supporting documents and audit trail",
    ],
  },
  "/ingest/geometry": {
    title: "Geometry Validation",
    story: "GEO-5.3",
    purpose: "Validation results for imported geographic boundaries with flagged geometry issues.",
    capabilities: [
      "View validation results: self-intersections, out-of-bounds coordinates, ring failures",
      "Inspect failing geometries on map with highlighted problematic segments",
      "Check winding-order normalization status for large polygons",
      "Filter by error severity and validation stage (fetch, normalize, publish)",
      "Export validation report with repair recommendations for manual fixes",
    ],
  },
  "/ingest/seed": {
    title: "Seed Data",
    story: "GEO-4.1",
    purpose: "Seed dataset import history, verification status, and reconciliation outcomes.",
    capabilities: [
      "View seed import manifest with version, checksums, and generated timestamp",
      "Verify exactly 16 seed regions and 261 unique districts loaded",
      "Check verification status (SEED_NEEDS_CANONICAL_RECONCILIATION vs CANONICAL)",
      "Re-run seed import to verify idempotency produces zero net changes",
      "Export seed deltas and reconciliation status for manual review",
    ],
  },
  "/review": {
    title: "Review Queue",
    story: "GEO-17.6",
    dependsOn: "GEO-5.4",
    purpose: "Main queue for reviewing data quality issues and proposed changes.",
    capabilities: [
      "Filter and prioritize flagged records by quality score and issue type",
      "View proposed patches with side-by-side diffs and source payload",
      "Approve, reject, or request changes on review items",
      "Add reviewer comments and assign to stewards",
    ],
  },
  "/review/change-requests": {
    title: "Change Requests",
    story: "GEO-17.6",
    dependsOn: "GEO-5.4",
    purpose: "List and detail all pending change requests for geographic data.",
    capabilities: [
      "Search and filter change requests by submitter, region, type, and status",
      "View proposed modifications to regions, districts, places, and boundaries",
      "Export change request reports with audit trail and decision history",
      "Bulk transition change requests through approval workflow states",
    ],
  },
  "/review/submissions": {
    title: "Community Submissions",
    purpose: "Review and moderate corrections submitted by community members.",
    capabilities: [
      "View unreviewed community submissions with evidence attachments",
      "Compare submitted corrections against canonical data with highlighted diffs",
      "Accept or reject submissions with public feedback to submitters",
      "Track submission acceptance rate and contributor reputation",
    ],
  },
  "/review/drafts": {
    title: "My Drafts",
    story: "GEO-17.7",
    dependsOn: "GEO-6.3",
    purpose: "Manage draft dataset versions through validation and approval gates.",
    capabilities: [
      "Create and edit draft dataset versions with version naming and metadata",
      "Run validation gates on draft versions before submission for review",
      "Compose and edit change logs documenting additions, merges, and boundary changes",
      "Publish approved drafts as versioned releases or rollback published versions",
    ],
  },
  "/review/evidence": {
    title: "Evidence Locker",
    story: "GEO-17.6",
    dependsOn: "GEO-5.4",
    purpose: "Store and manage supporting evidence and attachments for data reviews.",
    capabilities: [
      "Upload photos, surveys, maps, and documents as evidence for change requests",
      "Organize evidence by geographic location, data source, and collection date",
      "Link evidence to specific places, districts, and review items",
      "Generate evidence summaries and confidence scores for review prioritization",
    ],
  },
  "/releases/versions": {
    title: "Dataset Versions",
    purpose: "View published and draft dataset versions with metadata, checksums and source provenance.",
    capabilities: [
      "View published and draft dataset versions with checksums, timestamps and provenance",
      "Download complete dataset exports in JSON, CSV, GeoJSON or Parquet format",
      "Review version metadata tracking GeoNames, geoBoundaries and GSS sources",
      "Sort versions by status, date or coverage across regions and districts",
    ],
  },
  "/releases/pipeline": {
    title: "Release Pipeline",
    story: "GEO-17.7",
    dependsOn: "GEO-6.3 Release, rollback & changelog",
    purpose: "Manage dataset release workflow transitions from draft through validation, approval to publication.",
    capabilities: [
      "Transition versions through validation gates and approve for publication",
      "Run pre-release validation checks on regions, districts and geographic coverage",
      "Publish approved versions to production as canonical Ghanaian geography",
      "Rollback a published version to restore previous dataset if needed",
    ],
  },
  "/releases/validation": {
    title: "Validation Gates",
    purpose: "Execute and review validation gates that dataset releases must pass before publication.",
    capabilities: [
      "Execute validation suite on candidate versions before release publication",
      "Review validation results for schema, coverage and geometry validity",
      "Drill into specific validation failures affecting Ghana locations",
      "Monitor pass/fail status across all validation gates",
    ],
  },
  "/releases/diff": {
    title: "Version Diff",
    purpose: "Compare dataset versions to identify additions, removals and changes across geography.",
    capabilities: [
      "Compare versions showing additions, removals and changes to Ghana locations",
      "Filter by entity type: regions, districts, places, roads, POIs",
      "Track source changes from GeoNames, geoBoundaries, OSM and GNHR",
      "Identify and follow merged place redirects between versions",
    ],
  },
  "/releases/changelog": {
    title: "Changelog Composer",
    story: "GEO-17.7",
    dependsOn: "GEO-6.3 Release, rollback & changelog",
    purpose: "Author and manage dataset release changelog entries describing changes for public communication.",
    capabilities: [
      "Author release notes documenting additions, merges and boundary changes",
      "Auto-generate changelogs from diffs and edit before public release",
      "Publish official changelogs to the public API and documentation",
      "Manage archived changelogs and correct published release notes",
    ],
  },
  "/releases/exports": {
    title: "Exports & Downloads",
    story: "GEO-6.4",
    dependsOn: "GEO-6.4 Bulk export pipeline",
    purpose: "Manage bulk dataset export jobs in multiple formats with checksums and attribution.",
    capabilities: [
      "Trigger versioned exports in JSON, CSV, GeoJSON and Parquet formats",
      "Verify downloads with checksums and confirm ODbL/CC-BY attribution included",
      "Monitor export job status and access complete data package metadata",
      "Manage download endpoints and CDN caching for dataset distribution",
    ],
  },
  "/search-ops/tester": {
    title: "Query Tester",
    purpose: "Test and debug search queries against the index with real-time feedback.",
    capabilities: [
      "Execute test queries and view ranked results with confidence scores",
      "Inspect match explanations and relevance factors for each result",
      "Filter by district/region to test contextual ranking behavior",
      "Compare query performance metrics and execution time",
      "Export test results and queries for analysis",
    ],
  },
  "/search-ops/ranking": {
    title: "Ranking & Boosts",
    purpose: "Configure search relevance scoring and field-level boost factors.",
    capabilities: [
      "Adjust Atlas Search and Typesense index scoring parameters",
      "Apply proximity and district/region context boosts",
      "Tune typo-tolerance and abbreviation normalization thresholds",
      "Test ranking changes against golden-case queries before publishing",
      "Audit ranking changes with timestamps and rationale",
    ],
  },
  "/search-ops/synonyms": {
    title: "Synonyms & Abbreviations",
    purpose: "Manage search term synonyms and Ghanaian place-name abbreviations.",
    capabilities: [
      "Add, edit, and deprecate synonym pairs for places and localities",
      "Configure abbreviation mappings (Adenta ↔ Adentan, Comm ↔ Community)",
      "Set synonym priority and domain (region, district, or global)",
      "Bulk import synonym lists and validate for conflicts",
      "Test queries against active synonyms in Query Tester",
    ],
  },
  "/search-ops/gaps": {
    title: "Zero-Result Queries",
    purpose: "Track and analyze queries that return zero results to improve coverage.",
    capabilities: [
      "View and filter zero-result queries by date, frequency, and region",
      "Identify missing places or name variants causing gaps",
      "Propose new aliases or index entries to close gaps",
      "Bulk-mark queries as resolved or out-of-scope",
      "Export gap analysis for data steward review",
    ],
  },
  "/search-ops/eval": {
    title: "Geocoder Eval Sets",
    purpose: "Maintain geocoding evaluation datasets to verify search quality.",
    capabilities: [
      "Create labeled test sets with expected results for known place queries",
      "Run batch geocoding tests against the evaluation set",
      "Compare results by protocol (REST, GraphQL) and dataset version",
      "Track precision, recall, and F1 score over time",
      "Block dataset releases that degrade eval-set performance",
    ],
  },
  "/search-ops/index": {
    title: "Index Status",
    story: "GEO-17.10",
    dependsOn: "GEO-20.1",
    purpose: "Monitor search index health, freshness, and query performance metrics.",
    capabilities: [
      "Display index document count, size, and last-refreshed timestamp",
      "Show p50/p95/p99 latency for search, autocomplete, and reverse-geocode",
      "Monitor index lag relative to database dataset version",
      "Alert on stale indexes or degraded query performance",
      "Trigger index rebuild or failover to Typesense if Atlas Search degrades",
    ],
  },
  "/developers/orgs": {
    title: "Organizations",
    story: "GEO-17.8",
    dependsOn: "GEO-9.3",
    purpose: "Manage developer organizations including members, roles, and settings.",
    capabilities: [
      "Search organizations by name and view summary metrics",
      "View organization members and assigned roles",
      "Suspend organizations and revoke all associated keys",
      "View organization-level API quota usage and limits",
      "Transfer organizational ownership",
    ],
  },
  "/developers/users": {
    title: "Developer Users",
    purpose: "View and manage individual developer user accounts and access permissions.",
    capabilities: [
      "Search developer users by name, email, and organization",
      "View account status, created date, and last activity timestamp",
      "Reset passwords and force MFA re-enrollment",
      "View user's organizations, applications, and API keys",
      "Audit user login history and security events",
      "Disable or reinstate user accounts",
    ],
  },
  "/developers/apps": {
    title: "Applications",
    story: "GEO-17.8",
    dependsOn: "GEO-9.3",
    purpose: "Search and manage developer applications with test/live environment controls.",
    capabilities: [
      "Search applications by name, organization, and status",
      "View application configuration, rate-limit plan, and environment",
      "Suspend applications and revoke all associated API keys",
      "View application-level usage and quota consumption",
      "Switch between test and live environments",
      "Transfer application ownership between organizations",
    ],
  },
  "/developers/keys": {
    title: "API Keys",
    story: "GEO-17.8",
    dependsOn: "GEO-9.3",
    purpose: "Search and manage API keys with revocation, rotation, and scope controls.",
    capabilities: [
      "Search API keys by application, status, type, and created date",
      "View key scope, expiry, last used date, and origin restrictions",
      "Revoke keys instantly across REST, GraphQL, and gRPC",
      "Rotate key secrets for compromised or stale credentials",
      "Filter keys by type (Browser, Server, Test) and suspension status",
      "Suspend keys and view their usage history",
    ],
  },
  "/developers/scopes": {
    title: "Scopes & Permissions",
    purpose: "Define and manage API scope permissions available to developer applications.",
    capabilities: [
      "Create and document custom API scope definitions",
      "Manage scope hierarchy and access level rules",
      "View scope usage across applications and developer keys",
      "Disable scopes with migration guidance for affected keys",
      "Audit scope definition changes and review approvals",
      "Edit scope descriptions and resource access boundaries",
    ],
  },
  "/developers/plans": {
    title: "Rate-Limit Plans",
    story: "GEO-17.9",
    dependsOn: "GEO-9.6",
    purpose: "Configure rate-limit plans and fair-use quotas for all developer applications.",
    capabilities: [
      "Edit default fair-use limits for all developers without deploy",
      "Set per-cost-class rate-limit ceilings and thresholds",
      "Grant documented exemptions for research/government integrations",
      "View fair-use changes in audit log with reasons recorded",
      "Monitor usage trends to recommend limit adjustments",
      "Override limits instantly upon approval",
    ],
  },
  "/developers/logs": {
    title: "Request Logs",
    purpose: "View API request logs for debugging and monitoring developer applications.",
    capabilities: [
      "Filter logs by date, protocol, endpoint, and response status",
      "Search by application ID, API key prefix, or request ID",
      "View request latency, response size, and quota cost impact",
      "Export logs in CSV/JSON format with custom retention options",
      "Automatically redact secrets and authorization headers",
      "Identify usage patterns and detect abuse anomalies",
    ],
  },
  "/ops/health": {
    title: "Service Health",
    story: "GEO-17.10",
    dependsOn: "GEO-20.1",
    purpose: "Monitor real-time service health status, latency, error rates and system resource utilization.",
    capabilities: [
      "View aggregate service health status and component availability",
      "Monitor request latency percentiles (p50/p95/p99) across all protocols",
      "Track error rate and error-budget consumption",
      "Configure threshold alerts for health metrics",
    ],
  },
  "/ops/queues": {
    title: "Queues & Workers",
    story: "GEO-17.10",
    purpose: "Monitor background worker queue depth, job status and processing performance.",
    capabilities: [
      "View current queue depth and pending job counts",
      "Monitor worker availability and processing throughput",
      "Inspect individual job status and logs",
      "Trigger manual job retry or pause queues",
      "Set queue depth alerts and throughput thresholds",
    ],
  },
  "/ops/dlq": {
    title: "Outbox & Dead Letters",
    purpose: "Manage undelivered messages in the outbox and dead-letter queue with replay capability.",
    capabilities: [
      "List failed outbox messages with reason and timestamp",
      "View dead-letter queue contents and failure details",
      "Replay individual messages or batch messages back to queues",
      "Export DLQ for post-mortem analysis",
      "Configure DLQ retention and archival policies",
    ],
  },
  "/ops/freshness": {
    title: "ETL Freshness",
    story: "GEO-17.10",
    purpose: "Track ETL pipeline freshness, import lag and dataset update recency across all sources.",
    capabilities: [
      "View last-run timestamp for each ETL adapter (GNHR, GSS, OSM, GeoNames)",
      "Monitor ETL lag and alert on stale data beyond SLA threshold",
      "Inspect import run history with record counts and reconciliation conflicts",
      "Trigger manual import or adjust ETL schedule",
      "Track data freshness per source and dataset version",
    ],
  },
  "/ops/slo": {
    title: "SLOs & Error Budgets",
    story: "GEO-20.4",
    purpose: "Display SLO targets and error budgets for public API availability and data publishing pipeline.",
    capabilities: [
      "View 99.9% availability target vs actual uptime for REST, GraphQL and gRPC",
      "Monitor error budget consumption for read API and publishing pipeline separately",
      "Track SLO compliance by protocol and endpoint",
      "Set escalation alerts when error budget drops below threshold",
      "Export SLO reports for stakeholder review",
    ],
  },
  "/ops/performance": {
    title: "Latency & Traffic",
    story: "GEO-17.10",
    purpose: "Analyze API latency, traffic patterns and database query performance under load.",
    capabilities: [
      "View request rate, latency distribution and protocol breakdown",
      "Monitor database query latency and identify slow queries",
      "Track cache hit rate and search index performance",
      "Drill into geography-specific traffic patterns by region/district",
      "Configure performance baselines and latency SLA alerts",
    ],
  },
  "/ops/database": {
    title: "Database",
    story: "GEO-17.10",
    purpose: "Monitor MongoDB Atlas cluster health, replication status and resource consumption.",
    capabilities: [
      "View replica set status and node availability",
      "Monitor document growth by collection and storage usage",
      "Track index efficiency and unused indexes",
      "Inspect slow query logs and connection pool status",
      "Trigger backups and view restore-point availability",
    ],
  },
  "/ops/flags": {
    title: "Feature Flags",
    purpose: "Enable or disable features and experiment toggles without code deployment.",
    capabilities: [
      "Create and manage feature flags with percentage rollouts",
      "Target flags by environment, organization or application",
      "View flag audit history and rollout analytics",
      "Enable gradual rollout with kill-switch capability",
      "Archive and clean up obsolete flags",
    ],
  },
  "/ops/environments": {
    title: "Environments",
    purpose: "Configure and manage infrastructure environments (local, test, sandbox, staging, production).",
    capabilities: [
      "View environment configuration and deployed service versions",
      "Manage environment variables and secrets across deployments",
      "Monitor environment-specific database and cache instances",
      "Trigger environment promotion and deployment pipelines",
      "Compare configuration diffs between environments",
    ],
  },
  "/security/audit": {
    title: "Audit Log",
    story: "GEO-17.11",
    dependsOn: "GEO-9.7",
    purpose: "View immutable audit trail of privileged actions: regions, districts, places, datasets, API keys, releases.",
    capabilities: [
      "Filter audit entries by actor, action type, date range, affected resource",
      "View before/after state for each mutating action",
      "Export audit log as CSV for compliance and archival",
      "Search entries by request ID or resource ID",
      "Review IP address and timestamp for each mutation",
    ],
  },
  "/security/events": {
    title: "Security Events",
    story: "GEO-9.8",
    dependsOn: "GEO-9.7",
    purpose: "Monitor security alerts: unusual key usage, quota spikes, failed admin authentication.",
    capabilities: [
      "View failed login attempts with timestamp, actor, IP",
      "Alert on quota spike anomalies and usage patterns",
      "See suspicious API key activity flagged by system",
      "Export security event log for analysis",
      "View event severity and recommended actions",
    ],
  },
  "/security/access-reviews": {
    title: "Access Reviews",
    purpose: "Periodically review and audit admin role assignments across the organization.",
    capabilities: [
      "List all admins with their current roles and region scope",
      "Review role assignment provisioning history and changes",
      "Initiate access review cycles for compliance audit",
      "Request or approve role elevation with justification",
      "Identify dormant or inactive admin accounts for remediation",
    ],
  },
  "/security/sessions": {
    title: "Admin Sessions",
    story: "GEO-9.2",
    dependsOn: "GEO-9.2",
    purpose: "Monitor and revoke active admin sessions across the platform.",
    capabilities: [
      "List all active admin sessions with login time, IP, user agent",
      "Revoke individual sessions immediately for security",
      "Revoke all sessions for a user for password reset scenarios",
      "Detect concurrent logins from different IP addresses",
      "Force re-authentication on next admin portal access",
    ],
  },
  "/security/mfa": {
    title: "MFA & Passkey Policy",
    story: "GEO-9.2",
    dependsOn: "GEO-9.2",
    purpose: "Enforce and manage multi-factor authentication across admin roles.",
    capabilities: [
      "Require MFA for DATA_ADMIN, SECURITY_AUDITOR, SUPER_ADMIN roles",
      "View MFA enrollment status and method (passkey or TOTP) per admin",
      "Reset MFA for locked-out admins, issue temporary bypass codes",
      "Enforce MFA policy mandatory on next login",
      "Audit MFA enrollment, changes, and recovery code generation",
    ],
  },
  "/security/network": {
    title: "Network & CORS",
    story: "GEO-21.3",
    dependsOn: "GEO-21.3",
    purpose: "Configure API origin restrictions, CORS policies, and network access controls.",
    capabilities: [
      "Manage CORS allowed origins for REST, GraphQL, gRPC endpoints",
      "Set origin allow-lists and IP restrictions for browser API keys",
      "Configure HTTP security headers (HSTS, CSP, CSRF tokens)",
      "View access patterns by geographic region and source IP",
      "Monitor and block suspicious network access attempts",
    ],
  },
  "/content/changelog": {
    title: "Public Changelog",
    purpose: "Compose and publish public changelog entries for API and dataset releases.",
    capabilities: [
      "Create and edit version-specific changelog entries",
      "Coordinate with release workflow to auto-generate API changes",
      "Publish changelog to public marketing site",
      "Track dataset version changes and migrations",
      "Preview changelog before publication",
    ],
  },
  "/content/docs": {
    title: "Documentation Pages",
    purpose: "Author and manage technical documentation pages served on the public docs hub.",
    capabilities: [
      "Create, edit, and organize documentation pages",
      "Manage code snippet examples and quick starts",
      "Set page metadata, ordering, and visibility",
      "Preview docs in all three materials before publishing",
      "Update documentation hierarchy and navigation",
    ],
  },
  "/content/roadmap": {
    title: "Roadmap",
    purpose: "Manage and communicate the product roadmap to developers.",
    capabilities: [
      "Define and update roadmap milestones and epics",
      "Set feature maturity levels and release timelines",
      "Mark completed vs. planned work",
      "Publish roadmap updates to the public site",
      "Link roadmap items to Specification v2 waves",
    ],
  },
  "/content/coverage": {
    title: "Coverage Page Data",
    purpose: "Manage and display geographic coverage statistics and data source information.",
    capabilities: [
      "Update coverage statistics for regions and districts",
      "Manage data source registry and license attributions",
      "Document dataset limitations and boundaries",
      "Display provenance details for canonical data",
      "Show coverage maps by MMDA and place type",
    ],
  },
  "/content/status": {
    title: "Status Notices",
    story: "GEO-20.5",
    dependsOn: "GEO-20.1 OpenTelemetry observability",
    purpose: "Post operational status notices and incident communications for the public API.",
    capabilities: [
      "Create scheduled maintenance and incident notices",
      "Update real-time service status indicators",
      "Publish incident postmortems and resolutions",
      "Manage incident history and timeline",
      "Notify developers of service disruptions",
    ],
  },
};
