#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { examples } from "./manifest.mjs";

const root = resolve(import.meta.dirname, "../..");
const outputPath = resolve(root, "apps/web/src/content/sdk-docs.generated.ts");
const coreSource = readFileSync(resolve(root, "packages/core/src/index.ts"), "utf8");
const apiVersion = coreSource.match(/export const API_VERSION = "([^"]+)"/)?.[1];
const testedDatasetVersion = coreSource.match(/export const TESTED_DATASET_VERSION = "([^"]+)"/)?.[1];
if (!apiVersion || !testedDatasetVersion) throw new Error("Unable to read SDK compatibility versions from @ghanageo/core");
const payload = examples.map((example) => ({
  ...example,
  code: readFileSync(resolve(root, example.source), "utf8").trim(),
}));
const output = `/* Generated by scripts/docs-sdk/generate.mjs. Do not edit. */\n` +
  `export const SDK_API_VERSION = ${JSON.stringify(apiVersion)} as const;\n` +
  `export const SDK_TESTED_DATASET_VERSION = ${JSON.stringify(testedDatasetVersion)} as const;\n` +
  `export const SDK_EXAMPLES = ${JSON.stringify(payload, null, 2)} as const;\n`;

if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(outputPath, "utf8"); } catch {}
  if (current !== output) {
    console.error("SDK documentation is stale. Run: node scripts/docs-sdk/generate.mjs");
    process.exit(1);
  }
  console.log(`SDK documentation matches ${payload.length} tested example sources.`);
} else {
  writeFileSync(outputPath, output);
  console.log(`Generated ${payload.length} SDK quick starts.`);
}
