// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Coordinate struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type DatasetVersion struct {
	Version     string  `json:"version"`
	Status      string  `json:"status"`
	PublishedAt *string `json:"publishedAt,omitempty"`
	Changelog   *string `json:"changelog,omitempty"`
	Checksum    *string `json:"checksum,omitempty"`
}

type District struct {
	ID                 string             `json:"id"`
	Code               *string            `json:"code,omitempty"`
	Name               string             `json:"name"`
	Type               *string            `json:"type,omitempty"`
	Capital            *string            `json:"capital,omitempty"`
	Region             *Region            `json:"region"`
	Centroid           *Coordinate        `json:"centroid,omitempty"`
	Status             Status             `json:"status"`
	VerificationStatus VerificationStatus `json:"verificationStatus"`
	Provenance         *Provenance        `json:"provenance"`
	DatasetVersion     string             `json:"datasetVersion"`
	Boundary           map[string]any     `json:"boundary,omitempty"`
	Places             *PlaceConnection   `json:"places"`
}

type DistrictConnection struct {
	Edges          []DistrictEdge `json:"edges"`
	Nodes          []District     `json:"nodes"`
	PageInfo       *PageInfo      `json:"pageInfo"`
	DatasetVersion string         `json:"datasetVersion"`
}

type DistrictEdge struct {
	Node   *District `json:"node"`
	Cursor string    `json:"cursor"`
}

type NearbyResult struct {
	Place          *Place  `json:"place"`
	DistanceMeters float64 `json:"distanceMeters"`
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Place struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	NormalizedName     string             `json:"normalizedName"`
	Type               PlaceType          `json:"type"`
	Aliases            []PlaceAlias       `json:"aliases"`
	Region             *Region            `json:"region,omitempty"`
	District           *District          `json:"district,omitempty"`
	Parent             *Place             `json:"parent,omitempty"`
	Children           *PlaceConnection   `json:"children"`
	Centroid           *Coordinate        `json:"centroid,omitempty"`
	Boundary           map[string]any     `json:"boundary,omitempty"`
	Population         *int               `json:"population,omitempty"`
	Status             Status             `json:"status"`
	VerificationStatus VerificationStatus `json:"verificationStatus"`
	Provenance         *Provenance        `json:"provenance"`
	DatasetVersion     string             `json:"datasetVersion"`
}

// An alternative name, preserving the true Twi, Ga or Ewe orthography.
type PlaceAlias struct {
	Value       string  `json:"value"`
	Type        *string `json:"type,omitempty"`
	Language    *string `json:"language,omitempty"`
	IsPreferred bool    `json:"isPreferred"`
}

type PlaceConnection struct {
	Edges          []PlaceEdge `json:"edges"`
	Nodes          []Place     `json:"nodes"`
	PageInfo       *PageInfo   `json:"pageInfo"`
	DatasetVersion string      `json:"datasetVersion"`
}

type PlaceEdge struct {
	Node   *Place `json:"node"`
	Cursor string `json:"cursor"`
}

// Where a record came from. A record without provenance cannot be published.
type Provenance struct {
	SourceID    string  `json:"sourceId"`
	SourceURL   *string `json:"sourceUrl,omitempty"`
	RetrievedAt *string `json:"retrievedAt,omitempty"`
}

type Query struct {
}

type Region struct {
	ID                 string             `json:"id"`
	Code               *string            `json:"code,omitempty"`
	Name               string             `json:"name"`
	CountryCode        string             `json:"countryCode"`
	Capital            *string            `json:"capital,omitempty"`
	Centroid           *Coordinate        `json:"centroid,omitempty"`
	Status             Status             `json:"status"`
	VerificationStatus VerificationStatus `json:"verificationStatus"`
	Provenance         *Provenance        `json:"provenance"`
	DatasetVersion     string             `json:"datasetVersion"`
	// Costs more than a scalar field: it is a full geometry fetch.
	Boundary  map[string]any      `json:"boundary,omitempty"`
	Districts *DistrictConnection `json:"districts"`
}

type RegionConnection struct {
	Edges          []RegionEdge `json:"edges"`
	Nodes          []Region     `json:"nodes"`
	PageInfo       *PageInfo    `json:"pageInfo"`
	DatasetVersion string       `json:"datasetVersion"`
}

type RegionEdge struct {
	Node   *Region `json:"node"`
	Cursor string  `json:"cursor"`
}

// Coordinates outside Ghana return empty fields, not an error.
type ReverseGeocodeResult struct {
	Region         *Region   `json:"region,omitempty"`
	District       *District `json:"district,omitempty"`
	Nearby         []Place   `json:"nearby"`
	DatasetVersion string    `json:"datasetVersion"`
}

type SearchConnection struct {
	Nodes          []SearchResult `json:"nodes"`
	PageInfo       *PageInfo      `json:"pageInfo"`
	DatasetVersion string         `json:"datasetVersion"`
}

// A search hit. `score` and `matchReason` are required by Spec 10: an ambiguous
// query returns several candidates with their confidence rather than a guess.
type SearchResult struct {
	Place       *Place  `json:"place"`
	Score       float64 `json:"score"`
	MatchReason *string `json:"matchReason,omitempty"`
}

// Human geography. Ghana is deliberately not modelled as country/state/city.
type PlaceType string

const (
	PlaceTypeCity            PlaceType = "CITY"
	PlaceTypeTown            PlaceType = "TOWN"
	PlaceTypeVillage         PlaceType = "VILLAGE"
	PlaceTypeCommunity       PlaceType = "COMMUNITY"
	PlaceTypeSuburb          PlaceType = "SUBURB"
	PlaceTypeNeighbourhood   PlaceType = "NEIGHBOURHOOD"
	PlaceTypeHamlet          PlaceType = "HAMLET"
	PlaceTypeSettlement      PlaceType = "SETTLEMENT"
	PlaceTypeLocality        PlaceType = "LOCALITY"
	PlaceTypeRegionalCapital PlaceType = "REGIONAL_CAPITAL"
)

var AllPlaceType = []PlaceType{
	PlaceTypeCity,
	PlaceTypeTown,
	PlaceTypeVillage,
	PlaceTypeCommunity,
	PlaceTypeSuburb,
	PlaceTypeNeighbourhood,
	PlaceTypeHamlet,
	PlaceTypeSettlement,
	PlaceTypeLocality,
	PlaceTypeRegionalCapital,
}

func (e PlaceType) IsValid() bool {
	switch e {
	case PlaceTypeCity, PlaceTypeTown, PlaceTypeVillage, PlaceTypeCommunity, PlaceTypeSuburb, PlaceTypeNeighbourhood, PlaceTypeHamlet, PlaceTypeSettlement, PlaceTypeLocality, PlaceTypeRegionalCapital:
		return true
	}
	return false
}

func (e PlaceType) String() string {
	return string(e)
}

func (e *PlaceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlaceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlaceType", str)
	}
	return nil
}

func (e PlaceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PlaceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PlaceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Lifecycle state of a canonical record.
type Status string

const (
	StatusActive     Status = "ACTIVE"
	StatusDeprecated Status = "DEPRECATED"
	StatusMerged     Status = "MERGED"
)

var AllStatus = []Status{
	StatusActive,
	StatusDeprecated,
	StatusMerged,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusActive, StatusDeprecated, StatusMerged:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Status) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Status) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// How far a record has moved toward canonical truth.
//
// `SEED_NEEDS_CANONICAL_RECONCILIATION` marks bootstrap data awaiting official
// GNHR/GSS reconciliation. Such records are never promoted automatically.
type VerificationStatus string

const (
	VerificationStatusReference                        VerificationStatus = "REFERENCE"
	VerificationStatusSeedNeedsCanonicalReconciliation VerificationStatus = "SEED_NEEDS_CANONICAL_RECONCILIATION"
	VerificationStatusReviewed                         VerificationStatus = "REVIEWED"
	VerificationStatusCanonical                        VerificationStatus = "CANONICAL"
)

var AllVerificationStatus = []VerificationStatus{
	VerificationStatusReference,
	VerificationStatusSeedNeedsCanonicalReconciliation,
	VerificationStatusReviewed,
	VerificationStatusCanonical,
}

func (e VerificationStatus) IsValid() bool {
	switch e {
	case VerificationStatusReference, VerificationStatusSeedNeedsCanonicalReconciliation, VerificationStatusReviewed, VerificationStatusCanonical:
		return true
	}
	return false
}

func (e VerificationStatus) String() string {
	return string(e)
}

func (e *VerificationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VerificationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VerificationStatus", str)
	}
	return nil
}

func (e VerificationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VerificationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VerificationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
