package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/ghanageo/ghanageo/services/api/internal/domain/dataset"
	"github.com/ghanageo/ghanageo/services/api/internal/ports"
	"github.com/ghanageo/ghanageo/services/api/internal/transport/graphql/generated"
	"github.com/ghanageo/ghanageo/services/api/internal/transport/graphql/model"
)

// Region is the resolver for the region field.
func (r *districtResolver) Region(ctx context.Context, obj *model.District) (*model.Region, error) {
	if obj.Region == nil || obj.Region.ID == "" {
		return nil, nil
	}
	// Already hydrated (the caller asked for a district directly, not in a list).
	if obj.Region.DatasetVersion != "" {
		return obj.Region, nil
	}
	l := loadersFrom(ctx)
	if l == nil {
		return obj.Region, nil
	}
	full, err := l.Region(ctx, obj.Region.ID)
	if err != nil {
		// A dangling reference is data to report, not a reason to fail the
		// whole query — GraphQL's partial-data semantics exist for this.
		return obj.Region, nil
	}
	return regionOut(*full), nil
}

// Region is the resolver for the region field.
func (r *placeResolver) Region(ctx context.Context, obj *model.Place) (*model.Region, error) {
	if obj.Region == nil || obj.Region.ID == "" {
		return nil, nil
	}
	if obj.Region.DatasetVersion != "" {
		return obj.Region, nil
	}
	l := loadersFrom(ctx)
	if l == nil {
		return obj.Region, nil
	}
	full, err := l.Region(ctx, obj.Region.ID)
	if err != nil {
		return obj.Region, nil
	}
	return regionOut(*full), nil
}

// District is the resolver for the district field.
func (r *placeResolver) District(ctx context.Context, obj *model.Place) (*model.District, error) {
	if obj.District == nil || obj.District.ID == "" {
		return nil, nil
	}
	if obj.District.DatasetVersion != "" {
		return obj.District, nil
	}
	l := loadersFrom(ctx)
	if l == nil {
		return obj.District, nil
	}
	full, err := l.District(ctx, obj.District.ID)
	if err != nil {
		return obj.District, nil
	}
	return districtOut(*full), nil
}

// Region is the resolver for the region field.
func (r *queryResolver) Region(ctx context.Context, id string) (*model.Region, error) {
	out, err := r.GeoSvc.GetRegion(ctx, id)
	if err != nil {
		// A missing record is `null` plus an error entry, not a failed request:
		// GraphQL's partial-data semantics are the point of the protocol.
		return nil, err
	}
	return regionOut(*out), nil
}

// Regions is the resolver for the regions field.
func (r *queryResolver) Regions(ctx context.Context, first *int, after *string) (*model.RegionConnection, error) {
	page, err := r.GeoSvc.ListRegions(ctx, ports.ListParams{
		Limit: limitOf(first, 20), Cursor: strOf(after),
	})
	if err != nil {
		return nil, err
	}
	return regionConnection(page), nil
}

// District is the resolver for the district field.
func (r *queryResolver) District(ctx context.Context, id string) (*model.District, error) {
	out, err := r.GeoSvc.GetDistrict(ctx, id)
	if err != nil {
		return nil, err
	}
	return districtOut(*out), nil
}

// Districts is the resolver for the districts field.
func (r *queryResolver) Districts(ctx context.Context, regionID *string, query *string, first *int, after *string) (*model.DistrictConnection, error) {
	page, err := r.GeoSvc.ListDistricts(ctx, ports.DistrictFilter{
		ListParams: ports.ListParams{Limit: limitOf(first, 20), Cursor: strOf(after)},
		RegionID:   strOf(regionID),
		Query:      strOf(query),
	})
	if err != nil {
		return nil, err
	}
	return districtConnection(page), nil
}

// Place is the resolver for the place field.
func (r *queryResolver) Place(ctx context.Context, id string) (*model.Place, error) {
	out, err := r.GeoSvc.GetPlace(ctx, id)
	if err != nil {
		return nil, err
	}
	return placeOut(*out), nil
}

// Places is the resolver for the places field.
func (r *queryResolver) Places(ctx context.Context, districtID *string, regionID *string, typeArg *model.PlaceType, query *string, first *int, after *string) (*model.PlaceConnection, error) {
	f := ports.PlaceFilter{
		ListParams: ports.ListParams{Limit: limitOf(first, 20), Cursor: strOf(after)},
		DistrictID: strOf(districtID),
		RegionID:   strOf(regionID),
		Query:      strOf(query),
	}
	if typeArg != nil {
		f.Type = string(*typeArg)
	}
	page, err := r.GeoSvc.ListPlaces(ctx, f)
	if err != nil {
		return nil, err
	}
	return placeConnection(page), nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string, types []model.PlaceType, regionID *string, first *int) (*model.SearchConnection, error) {
	q := ports.SearchQuery{Text: query, Limit: limitOf(first, 20), RegionID: strOf(regionID)}
	// The schema allows several types; the use case takes one. Passing the
	// first is honest for now — accepting a list and silently applying one of
	// them would be worse than the current single-type behaviour.
	if len(types) > 0 {
		q.Type = string(types[0])
	}
	hits, err := r.SearchSvc.Search(ctx, q)
	if err != nil {
		return nil, err
	}
	return searchConnection(hits, r.SearchSvc.DatasetVersion()), nil
}

// Autocomplete is the resolver for the autocomplete field.
func (r *queryResolver) Autocomplete(ctx context.Context, query string, first *int) ([]model.SearchResult, error) {
	hits, err := r.SearchSvc.Autocomplete(ctx, query, limitOf(first, 10))
	if err != nil {
		return nil, err
	}
	return searchResults(hits), nil
}

// Geocode is the resolver for the geocode field.
func (r *queryResolver) Geocode(ctx context.Context, query string, first *int) ([]model.SearchResult, error) {
	hits, err := r.SearchSvc.Geocode(ctx, query, limitOf(first, 10))
	if err != nil {
		return nil, err
	}
	return searchResults(hits), nil
}

// Reverse is the resolver for the reverse field.
func (r *queryResolver) Reverse(ctx context.Context, latitude float64, longitude float64) (*model.ReverseGeocodeResult, error) {
	res, err := r.SearchSvc.Reverse(ctx, latitude, longitude)
	if err != nil {
		return nil, err
	}
	out := &model.ReverseGeocodeResult{
		Nearby:         make([]model.Place, 0, len(res.Nearby)),
		DatasetVersion: res.DatasetVersion,
	}
	if res.Region != nil {
		out.Region = regionOut(*res.Region)
	}
	if res.District != nil {
		out.District = districtOut(*res.District)
	}
	for _, p := range res.Nearby {
		out.Nearby = append(out.Nearby, *placeOut(p))
	}
	return out, nil
}

// Nearby is the resolver for the nearby field.
func (r *queryResolver) Nearby(ctx context.Context, latitude float64, longitude float64, radiusMeters *int, first *int) ([]model.NearbyResult, error) {
	radius := 5000
	if radiusMeters != nil && *radiusMeters > 0 {
		radius = *radiusMeters
	}
	places, err := r.GeoSvc.Nearby(ctx, latitude, longitude, radius, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	out := make([]model.NearbyResult, 0, len(places))
	for _, p := range places {
		n := model.NearbyResult{Place: placeOut(p)}
		// $nearSphere returns nearest-first but does not hand back the distance,
		// so it is computed here rather than reported as zero.
		if p.Centroid != nil {
			n.DistanceMeters = haversineMeters(latitude, longitude, p.Centroid.Latitude, p.Centroid.Longitude)
		}
		out = append(out, n)
	}
	return out, nil
}

// DatasetVersion is the resolver for the datasetVersion field.
func (r *queryResolver) DatasetVersion(ctx context.Context) (*model.DatasetVersion, error) {
	if r.DatasetSvc == nil {
		return &model.DatasetVersion{Version: r.GeoSvc.DatasetVersion(), Status: "published"}, nil
	}
	versions, err := r.DatasetSvc.List(ctx)
	if err != nil || len(versions) == 0 {
		return nil, err
	}
	return datasetVersionModel(versions[0]), nil
}

// DatasetVersions is the resolver for the datasetVersions field.
func (r *queryResolver) DatasetVersions(ctx context.Context, first *int, after *string) ([]model.DatasetVersion, error) {
	if r.DatasetSvc == nil {
		return []model.DatasetVersion{{Version: r.GeoSvc.DatasetVersion(), Status: "published"}}, nil
	}
	versions, err := r.DatasetSvc.List(ctx)
	if err != nil {
		return nil, err
	}
	limit := 20
	if first != nil && *first >= 0 && *first < limit {
		limit = *first
	}
	out := make([]model.DatasetVersion, 0, limit)
	started := after == nil || *after == ""
	for _, version := range versions {
		if !started {
			started = version.Version == *after
			continue
		}
		if len(out) == limit {
			break
		}
		out = append(out, *datasetVersionModel(version))
	}
	return out, nil
}

func datasetVersionModel(v dataset.Version) *model.DatasetVersion {
	publishedAt := v.PublishedAt
	var changelog *string
	if v.Changelog != "" {
		changelog = &v.Changelog
	}
	return &model.DatasetVersion{
		Version: v.Version, Status: string(v.Status), PublishedAt: &publishedAt, Changelog: changelog,
	}
}

// District returns generated.DistrictResolver implementation.
func (r *Resolver) District() generated.DistrictResolver { return &districtResolver{r} }

// Place returns generated.PlaceResolver implementation.
func (r *Resolver) Place() generated.PlaceResolver { return &placeResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	districtResolver struct{ *Resolver }
	placeResolver    struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	var _ = apierr.Internal
*/
